/**********************************************************************
 * Copyright (c) 2022 Hilscher Gesellschaft fuer Systemautomation mbH
 * See LICENSE file
 **********************************************************************/

const edgeSDK = require('../src/index');
const _get = require('lodash').get;
jest.mock('../src/client.js');

const suggestInvalid = {
    organisationId: 1,
    search: "valid",
    invalidAttribute: "invalid"
};

const suggestInvalidTwo = {
    organisationId: 1,
    search: 1,
    invalidAttribute: "invalid"
};

const calls = [
    ["devices.customFields.delete", [1, 1]],
    ["devices.notifications.delete", [1, 1]],
    ["devices.customFields.get", [1, 1]],
    ["devices.create", ["wrong"]],
    ["devices.onBoard", ["wrong"]],
    ["devices.onBoardWithKey", ["wrong"]],
    ["devices.notifications.deleteAll", [1]],
    ["devices.delete", [1]],
    ["devices.get", [1]],
    ["devices.getWithKey", [1]],
    ["devices.getChildren", [1]],
    ["devices.offBoard", [1]],
    ["devices.offBoardConfirm", [1]],
    ["devices.offBoardConfirm", [1, 1]],
    ["devices.create", ["w"]],
    ["devices.getAll", [{}, {}, {}, {}, {}, {}, {}, {}, {}]],
    ["devices.getWithGeolocation", ["w"]],
    ["devices.getWithGeolocation", [1, 1]],
    ["devices.getWithGeolocation", [1, "standard", 1]],
    ["devices.getWithGeolocation", [1, "standard", "name", 1]],
    ["devices.getStatusList", [
        [1, 1]
    ]],
    ["devices.methods", [1, 1]],
    ["devices.update", [1, 1]],
    ["devices.onBoard", [1]],
    ["devices.onBoardWithKey", [1]],
    ["devices.onboardSensorEdge", [1]],
    ["devices.enableDisable", [1, "w", 1]],
    ["devices.filter", [1]],
    ["devices.customFields.create", [1, 1]],
    ["devices.customFields.update", [1, 1, 1]],
    ["devices.notifications.create", [1, 1]],
    ["devices.notifications.getAll", ["w", 1, "w", "w", "w"]],
    ["devices.customFields.getAll", ["w", 1, "w", "w", "w"]],
    ["devices.containers.routes.delete", [1, 1]],
    ["devices.containers.routes.create", [1, 1]],
    ["devices.containers.routes.update", [1, 1, 1]],
    ["devices.containers.routes.getAll", [1]],
    ["devices.containers.routes.get", ["valid", 1]],
    ["devices.containers.routes.get", [1, "valid"]],
    ["devices.containers.routes.get", [1, 1]],
    ["devices.containers.get", ["valid", 1]],
    ["devices.containers.get", [1, "valid"]],
    ["devices.containers.getSystem", ["valid", 1]],
    ["devices.containers.getSystem", [1, "valid"]],
    ["devices.containers.getInstalled", [1]],
    ["devices.containers.getSystemInstalled", [1]],
    ["devices.containers.getSystemInstalled", ["w", 'invalid']],
    ["devices.containers.getSystemInstalled", ["w", 1, 'invalid']],
    ["devices.containers.getSystemInstalled", ["w", 1, 1, 1]],
    ["devices.containers.getSystemInstalled", ["w", 1, 1, 'valid', 1]],
    ["devices.containers.getInstalled", [1, "w", "w", 1, 1, 1]],
    ["devices.containers.getInstalled", [1, "w", "w", 1, 1, 1, 1]],
    ["devices.containers.getInstalled", [1, "w", "w", 1, 1, 1, 1, 1]],
    ["devices.containers.getDeployable", [1]],
    ["devices.containers.getDevicesPlatforms", [1]],
    ["devices.containers.getDevicesPlatforms", [[1, 1]]],
    ["devices.containers.delete", [1, "valid"]],
    ["devices.containers.create", [1, "valid", {}]],
    ["devices.containers.update", [1, "valid", {}]],
    ["devices.containers.properties", [1, "valid"]],
    ["devices.containers.deleteAll", [1]],
    ["devices.containers.deleteDeviceContainers", [1, 1]],
    ["devices.containers.getdeployableversions", [1, 1]],
    ["devices.containers.createList", [1, {}]],
    ["devices.containers.updateList", [1, {}]],
    ["devices.remote.create", [1, {}]],
    ["devices.remote.create", ["valid", "valid"]],
    ["devices.remote.status", [1]],
    ["devices.remote.credentials", [1]],
    ["devices.deploymentManifests.check", [1]],
    ["devices.deploymentManifests.check", [{}]],
    ["devices.deploymentManifests.deploy", [1]],
    ["devices.deploymentManifests.deploy", [{}]],
    ["devices.messages.getAll", [1, "w", "w"]],
    ["devices.messages.getAll", [1, "w", "w", 1]],
    ["devices.messages.getAll", [1, "w", "w", 1, 1]],
    ["devices.messages.getAll", [1, "w", "w", 1, 1, "w"]],
    ["devices.topics.getAll", [1, "w", "w"]],

    ["dashboards.create", ["w"]],
    ["dashboards.update", [1, "w"]],
    ["dashboards.get", [1]],
    ["dashboards.getAll", [{}]],
    ["dashboards.delete", [1]],
    ["dashboards.panels.create", [1, "w"]],
    ["dashboards.panels.update", [1, 1, "w"]],
    ["dashboards.panels.get", [1, 1]],
    ["dashboards.panels.getAll", [1]],
    ["dashboards.panels.delete", [1, 1]],
    ["dashboards.series.create", [1, 1, "w"]],
    ["dashboards.series.update", [1, 1, 1, "w"]],
    ["dashboards.series.get", [1, 1, 1]],
    ["dashboards.series.getAll", [1, 1]],
    ["dashboards.series.delete", [1, 1, 1]],

    ["containers.create", ["wrong"]],
    ["containers.delete", [1]],
    ["containers.delete", [1, "w"]],
    ["containers.get", [1]],
    ["containers.update", [1, 1]],
    ["containers.update", [1, 1]],
    ["containers.getAll", ["w", "w"]],
    ["containers.getAll", [1, "w"]],
    ["containers.getAll", [1, 1, 1]],
    ["containers.getAll", [1, 1, "w", 1]],
    ["containers.getAll", [1, 1, "w", 1, "w"]],
    ["containers.getAll", [1, 1, "w", 1, "w", 1]],
    ["containers.getAll", [1, 1, "w", 1, "w", 1, 1]],
    ["containers.getAll", [1, 1, "w", 1, "w", 1, 1, "w"]],
    ["containers.sharings.share", [1]],
    ["containers.sharings.share", ['w']],
    ["containers.sharings.unshare", ['w']],
    ["containers.sharings.unshare", [{}]],
    ["containers.sharings.get", ['w']],
    ["containers.sharings.get", [{}]],
    ["containers.sharings.getAll", [1]],
    ["containers.sharings.getAll", ['v', 'W']],
    ["containers.sharings.getAll", ['v', 1, 'w']],
    ["containers.sharings.getAll", ['v', 1, 1, 1]],
    ["containers.sharings.getAll", ['v', 1, 1, 'v', 1]],
    ["containers.sharings.update", ['w', {}]],
    ["containers.sharings.update", [1, 'w']],
    ["containers.sharings.update", [1, 1]],
    ["containers.versions.sharings.unshare", ['w', {}]],
    ["containers.versions.createversion", ["w", {}]],
    ["containers.versions.deleteversion", [1, 1]],
    ["containers.versions.getversion", [1, 1]],
    ["containers.versions.getallversions", [1]],
    ["containers.versions.getallversions", [1, 1]],
    ["containers.versions.getallversions", [1, 1, 1]],
    ["containers.versions.getallversions", [1, 1, 1, "name"]],
    ["containers.versions.getallversions", [1, 1, 1, "name", 1]],
    ["containers.versions.updateversion", ["w", "v", "v"]],
    ["containers.disable", [1, "w"]],
    ["containers.envVariables.getAll", [1]],
    ["containers.envVariables.getAll", [1, 1]],

    ["users.createself", ["wrong"]],
    ["users.createself", ["wrong", 1]],
    ["users.create", ["wrong"]],
    ["users.sensoredge.create", ["wrong"]],
    ["users.sensoredge.create", ["wrong", 1]],
    ["users.profile.update", ["wrong"]],
    ["users.profile.notificationEmails.add", ["wrong"]],
    ["users.profile.notificationEmails.add", [1]],
    ["users.profile.notificationEmails.getAll", ['w']],
    ["users.profile.notificationEmails.getAll", [1, 'w']],
    ["users.profile.notificationEmails.getAll", [1, 1, 1]],
    ["users.profile.notificationEmails.getAll", [1, 1, 'v', 1]],
    ["users.profile.notificationEmails.delete", ['w']],
    ["users.profile.notificationEmails.delete", [{}]],
    ["users.profile.notificationEmails.delete", [{}]],
    ["users.profile.notificationEmails.delete", [1, 1]],
    ["users.verifyusers", ["wrong"]],
    ["users.verifyusers", ["wrong", 1]],
    ["users.sensoredge.verify", ["wrong"]],
    ["users.sensoredge.getverify", [1]],
    ["users.sensoredge.getverify", [1, 1]],
    ["users.sensoredge.getverify", [1, 1]],
    ["users.getAll", [{}, {}, {}, {}, {}]],
    ["users.get", ["wrong", "wrong"]],
    ["users.getverify", [1]],
    ["users.getverify", [1, 1]],
    ["users.getverify", [1, 1, 1]],
    ["users.update", ["wrong", "wrong"]],
    ["users.sensoredge.completeRegistration", ["wrong"]],
    ["users.sensoredge.completeRegistration", ["wrong", 1]],
    ["users.delete", ["wrong"]],
    ["users.roles.add", [{}, {}, {}]],
    ["users.roles.delete", [{}, {}, {}]],
    ["users.roles.getAll", [{}, {}, {}, {}, {}, {}]],
    ["users.suggest", [suggestInvalid]],
    ["users.suggest", [suggestInvalidTwo]],
    ["users.invite.create", ['w']],
    ["users.invite.update", ['w']],
    ["users.invite.update", ['w', 1]],
    ["users.invite.getAll", [{}, {}, {}, {}, {}]],
    ["users.invite.revoke", [{}, 'w']],
    ["users.invite.delete", [true]],
    ["users.workspaces.getAll", [{}, {}, {}, {}, {}]],
    ["users.workspaces.delete", [{}, {}]],
    ["users.preferences.update", [1]],
    ["users.preferences.update", ["wrong"]],

    ["keys.create", ["wrong"]],
    ["keys.delete", [1]],
    ["keys.get", [1]],
    ["keys.update", [1, 1]],
    ["keys.getAll", [{}, {}, {}, {}, {}]],
    ["keys.createSensorEdgeKey", ["w"]],

    ["keys.getConnectionDevices", ['v']],
    ["keys.getConnectionDevices", ['v', 'v']],
    ["keys.getConnectionDevices", ['v', 'v', 1]],
    ["keys.getConnectionDevices", ['v', 'v', 1, 1]],
    ["keys.getConnectionDevices", ['v', 'v', 1, 1, 1]],
    ["keys.getConnectionDevices", ['v', 'v', 1, 1, [1]]],


    ["auth.resetPassword", [1]],
    ["auth.resetPassword", [1, 1]],
    ["auth.resetPassword", [1, 1, 1]],
    ["auth.setPassword", [1]],
    ["auth.setPassword", [1, 1]],
    ["auth.sso", [1]],
    ["auth.sso", ['v']],
    ["auth.twoFactor.verify", [1, 1, 1]],
    ["auth.twoFactor.verify", ['w', 'w', 1]],
    ["auth.twoFactor.verify", ['w', 1, 1]],
    ["auth.twoFactor.disable", [1]],
    ["auth.twoFactor.methods.add", [1]],
    ["auth.twoFactor.methods.delete", ['w', 'v']],
    ["auth.twoFactor.methods.delete", [1, 1]],
    ["auth.twoFactor.methods.select", ['w']],
    ["auth.twoFactor.methods.verify", [1, 1]],
    ["auth.twoFactor.methods.verify", ['w', 'w']],
    ["auth.twoFactor.methods.verify", ['w', 1]],

    ["organisation.get", ["w", "w"]],
    ["organisation.get", ["w"]],
    ["organisation.update", ["w", "w"]],
    ["organisation.create", ["w", "w"]],
    ["organisation.delete", ["w"]],
    ["organisation.getAll", ["w", "w"]],
    ["organisation.getAll", [1, "w"]],
    ["organisation.getAll", [1, 1, 1]],
    ["organisation.getAll", [1, 1, "w", 1]],
    ["organisation.getAll", [1, 1, "w", 'w', 1]],
    ["organisation.createUpgradeRequest", ['v', {}]],

    ["organisation.manifest.create", ['v', {}]],
    ["organisation.manifest.update", ['v', 'v', {}]],
    ["organisation.manifest.update", [1, 1, {}]],
    ["organisation.manifest.delete", ['v', 'v']],
    ["organisation.manifest.delete", [1, 1]],
    ["organisation.manifest.get", ['v', 'v']],
    ["organisation.manifest.get", [1, 1]],
    ["organisation.manifest.getAll", ['v']],
    ["organisation.manifest.getAll", [1, 'v']],
    ["organisation.manifest.getAll", [1, 1, 'v']],
    ["organisation.manifest.getAll", [1, 1, 1, 1]],
    ["organisation.manifest.getAll", [1, 1, 1, 'v', 1]],

    ["organisation.manifest.copyManifest", ["w"]],
    ["organisation.manifest.applyManifest", ['w', 'v', 'v']],
    ["organisation.manifest.applyManifest", [1, 1, 'v']],
    ["organisation.manifest.applyManifest", [1, 'v', 1]],
    ["organisation.manifest.applyManifest", [1, 'v', 'v', 'w']],
    ["organisation.manifest.applyManifest", [1, 'v', 'v', 1]],

    ["organisation.manifest.containers.add", ["w", 'v', 'v', {}]],
    ["organisation.manifest.containers.add", [1, 1, 'v', {}]],
    ["organisation.manifest.containers.add", [1, 'v', 1, {}]],
    ["organisation.manifest.containers.update", ["w", 'v', 'v', {}]],
    ["organisation.manifest.containers.update", [1, 1, 'v', {}]],
    ["organisation.manifest.containers.update", [1, 'v', 1, {}]],
    ["organisation.manifest.containers.delete", ["w", 'v', 'v']],
    ["organisation.manifest.containers.delete", [1, 1, 'v']],
    ["organisation.manifest.containers.delete", [1, 'v', 1]],
    ["organisation.manifest.containers.get", ["w", 'v', 'v']],
    ["organisation.manifest.containers.get", [1, 1, 'v']],
    ["organisation.manifest.containers.get", [1, 'v', 1]],
    ["organisation.manifest.containers.getAll", ["w", 'v']],
    ["organisation.manifest.containers.getAll", [1, 1]],
    ["organisation.manifest.containers.getAll", [1, 'v', "w"]],
    ["organisation.manifest.containers.getAll", [1, 'v', 1, 'w']],
    ["organisation.manifest.containers.getAll", [1, 'v', 1, 1, 1]],
    ["organisation.manifest.containers.getAll", [1, 'v', 1, 1, 'v', 1]],

    ["organisation.manifest.routes.add", ["w", 'v', {}]],
    ["organisation.manifest.routes.add", [1, 1, {}]],
    ["organisation.manifest.routes.update", ["w", 'v', 'v', {}]],
    ["organisation.manifest.routes.update", [1, 1, 'v', {}]],
    ["organisation.manifest.routes.update", [1, 'v', 1, {}]],
    ["organisation.manifest.routes.delete", ["w", 'v', 'v']],
    ["organisation.manifest.routes.delete", [1, 1, 'v']],
    ["organisation.manifest.routes.delete", [1, 'v', 1]],
    ["organisation.manifest.routes.get", ["w", 'v', 'v']],
    ["organisation.manifest.routes.get", [1, 1, 'v']],
    ["organisation.manifest.routes.get", [1, 'v', 1]],
    ["organisation.manifest.routes.getAll", ["w", 'v']],
    ["organisation.manifest.routes.getAll", [1, 1]],
    ["organisation.manifest.routes.getAll", [1, 'v', "w"]],
    ["organisation.manifest.routes.getAll", [1, 'v', 1, 'w']],
    ["organisation.manifest.routes.getAll", [1, 'v', 1, 1, 1]],
    ["organisation.manifest.routes.getAll", [1, 'v', 1, 1, 'v', 1]],

    ["roles.create", ["w", "w"]],
    ["roles.get", [{}, {}]],
    ["roles.update", ["w", {}, 1]],
    ["roles.getAll", [{}, {}, {}, {}, {}]],
    ["roles.delete", [{}, {}]],

    ["search.devices", [1]],
    ["search.devices", ["v", 1]],
    ["search.devices", ["v", [1]]],
    ["search.devices", ["v", "v", 1]],
    ["search.devices", ["v", "v", "fuzzy", "w"]],
    ["search.devices", ["v", "v", "fuzzy", 1, "w"]],
    ["search.devices", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.devices", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.containers", [1]],
    ["search.containers", ["v", 1]],
    ["search.containers", ["v", [1]]],
    ["search.containers", ["v", "v", 1]],
    ["search.containers", ["v", "v", "fuzzy", "w"]],
    ["search.containers", ["v", "v", "fuzzy", 1, "w"]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 1, "v"]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 1, false, 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 1, false, {}]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 1, false, false]],
    ["search.organisations", [1]],
    ["search.organisations", ["v", 1]],
    ["search.organisations", ["v", [1]]],
    ["search.organisations", ["v", "v", 1]],
    ["search.organisations", ["v", "v", "fuzzy", "w"]],
    ["search.organisations", ["v", "v", "fuzzy", 1, "w"]],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.users", [1]],
    ["search.users", ["v", 1]],
    ["search.users", ["v", [1]]],
    ["search.users", ["v", "v", 1]],
    ["search.users", ["v", "v", "fuzzy", "w"]],
    ["search.users", ["v", "v", "fuzzy", 1, "w"]],
    ["search.users", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.users", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.deploymentFilters", [1]],
    ["search.deploymentFilters", ["v", 1]],
    ["search.deploymentFilters", ["v", [1]]],
    ["search.deploymentFilters", ["v", "v", 1]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", "w"]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, "w"]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.deploymentJobs", [1]],
    ["search.deploymentJobs", ["v", 1]],
    ["search.deploymentJobs", ["v", [1]]],
    ["search.deploymentJobs", ["v", "v", 1]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", "w"]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, "w"]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.deploymentRollouts", ["v", 1]],
    ["search.deploymentRollouts", ["v", [1]]],
    ["search.deploymentRollouts", ["v", "v", 1]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", "w"]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, "w"]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.tenants", [1]],
    ["search.tenants", ["v", 1]],
    ["search.tenants", ["v", [1]]],
    ["search.tenants", ["v", "v", 1]],
    ["search.tenants", ["v", "v", "fuzzy", "w"]],
    ["search.tenants", ["v", "v", "fuzzy", 1, "w"]],
    ["search.tenants", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.tenants", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.keys", [1]],
    ["search.keys", ["v", 1]],
    ["search.keys", ["v", [1]]],
    ["search.keys", ["v", "v", 1]],
    ["search.keys", ["v", "v", "fuzzy", "w"]],
    ["search.keys", ["v", "v", "fuzzy", 1, "w"]],
    ["search.keys", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.keys", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.groups", [1]],
    ["search.groups", ["v", 1]],
    ["search.groups", ["v", [1]]],
    ["search.groups", ["v", "v", 1]],
    ["search.groups", ["v", "v", "fuzzy", "w"]],
    ["search.groups", ["v", "v", "fuzzy", 1, "w"]],
    ["search.groups", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.groups", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.groups", ["v", "v", "fuzzy", 1, 1, 'name', 1, 1]],


    ["permissions.devices", [
        [1, 1, 1]
    ]],
    ["permissions.containers", [
        [1, 1, 1]
    ]],
    ["permissions.organisations", [
        ["v", "v"]
    ]],
    ["permissions.users", [
        ["v", "v"]
    ]],
    ["permissions.roles", [1]],
    ["permissions.tenants", [
        ["v", "v"]
    ]],
    ["permissions.keys", [
        [1, 1, 1]
    ]],
    ["permissions.edgeos", [
        [1, 1, 1]
    ]],
    ["permissions.webhooks", [
        [1, 1, 1]
    ]],
    ["permissions.groups", [
        ["v", "v"]
    ]],

    ["permissions.devices", [1]],
    ["permissions.containers", [1]],
    ["permissions.organisations", [1]],
    ["permissions.users", [1]],
    ["permissions.tenants", [1]],
    ["permissions.keys", [1]],
    ["permissions.edgeos", [1]],
    ["permissions.permissions", [1]],
    ["permissions.webhooks", [1]],
    ["permissions.groups", ["v"]],

    ["edgeos.getAll", [{}, {}, {}, {}, {}, {}, {}, {}]],
    ["edgeos.create", [1]],
    ["edgeos.update", [1, 1]],
    ["edgeos.get", [1]],
    ["edgeos.delete", [1]],

    ["tenants.create", ["wrong"]],
    ["tenants.update", ["w", "w"]],
    ["tenants.get", ["w"]],
    ["tenants.getAll", [{}, {}, {}, {}]],
    ["tenants.delete", ["w"]],

    ["webhooks.create", ["w"]],
    ["webhooks.test", ["w"]],
    ["webhooks.test", [1]],
    ["webhooks.delete", [1]],
    ["webhooks.get", [1]],
    ["webhooks.update", [1, {}]],
    ["webhooks.update", [1, 'w']],
    ["webhooks.getAll", ['w']],
    ["webhooks.getAll", [1, 'w']],
    ["webhooks.getAll", [1, 'v', 'v']],
    ["webhooks.getAll", ["w"]],
    ["webhooks.getAll", [1, "w"]],
    ["webhooks.getAll", [1, "w", "w"]],
    ["webhooks.getAll", [1, 1, 1, 1]],
    ["webhooks.getAll", [1, 1, 1, 1, 1]],

    ["groups.get", ["w", "w"]],
    ["groups.get", ["w"]],
    ["groups.update", ["w", "w"]],
    ["groups.create", ["w", "w"]],
    ["groups.delete", ["w"]],
    ["groups.getGroupItems", ["w"],
        ["w"],
        ["w"],
        [1],
        [1],
        ["w"]
    ],
    ["groups.addDevice", ["w", 1]],
    ["groups.removeDevice", ["w", 1]],
    ["groups.addContainer", ["w", 1]],
    ["groups.removeContainer", ["w", 1]],
    ["groups.getAll", [{}, {}, {}, {}, {}, {}]],
    ["groups.getAll", [{}, {}, {}, {}, {}, "w"]],
    ["groups.getAll", ["w", {}, {}, {}, {}, "w"]],

    ["deployments.filters.create", [1]],
    ["deployments.filters.create", ["w"]],
    ["deployments.filters.getAll", [{}, {}, {}, {}, {}]],
    ["deployments.filters.update", [1, "w"]],
    ["deployments.filters.delete", [1]],
    ["deployments.filters.get", [1]],
    ["deployments.filters.execute", [1]],
    ["deployments.filters.execute", [{}, 'w']],
    ["deployments.filters.execute", [{}, 1, 'w']],
    ["deployments.filters.execute", [{}, 1, 1, 1]],
    ["deployments.filters.execute", [{}, 1, 1, "v", 1, 1]],

    ["deployments.jobs.create", [1]],
    ["deployments.jobs.update", [1, "w"]],
    ["deployments.jobs.delete", [1]],
    ["deployments.jobs.get", [1]],
    ["deployments.jobs.getAll", [{}, {}, {}, {}, {}]],
    ["deployments.jobs.execute", [1, 'v']],
    ["deployments.jobs.execute", ['v', 1]],
    ["deployments.jobs.execute", ['v', 'v', 'v']],
    ["deployments.jobs.executeByGroup", [1, 1]],
    ["deployments.jobs.executeByGroup", ['w', 'w']],
    ["deployments.jobs.executeByGroup", ['w', 1, 'w']],
    ["deployments.jobs.executeCustomSelect", [1]],
    ["deployments.jobs.executeCustomSelect", [1, 1]],
    ["deployments.jobs.executeCustomSelect", [1, 'v']],
    ["deployments.jobs.executeCustomSelect", ['v', 'v']],

    ["deployments.jobs.containers.add", [1, 1, {}]],
    ["deployments.jobs.containers.update", [1, 1, {}]],
    ["deployments.jobs.containers.delete", [1, 1]],
    ["deployments.jobs.containers.get", [1, 1]],
    ["deployments.jobs.containers.getAll", [1]],
    ["deployments.jobs.containers.getAll", [1, 1]],
    ["deployments.jobs.containers.getAll", [1, 1, 1]],
    ["deployments.jobs.containers.getAll", [1, 1, 1, "name"]],
    ["deployments.jobs.containers.getAll", [1, 1, 1, "name", 1]],

    ["deployments.jobs.containers.methods.add", [1, 'v', {}]],
    ["deployments.jobs.containers.methods.add", ['v', 1, {}]],
    ["deployments.jobs.containers.methods.update", [1, 'v', 'v', {}]],
    ["deployments.jobs.containers.methods.update", ['v', 1, 'v', {}]],
    ["deployments.jobs.containers.methods.update", ['v', 'v', 1, {}]],
    ["deployments.jobs.containers.methods.delete", [1, 'v', 'v']],
    ["deployments.jobs.containers.methods.delete", ['v', 1, 'v']],
    ["deployments.jobs.containers.methods.delete", ['v', 'v', 1]],
    ["deployments.jobs.containers.methods.get", [1, 'v', 'v']],
    ["deployments.jobs.containers.methods.get", ['v', 1, 'v']],
    ["deployments.jobs.containers.methods.get", ['v', 'v', 1]],
    ["deployments.jobs.containers.methods.getAll", [1, 'v']],
    ["deployments.jobs.containers.methods.getAll", ['v', 1]],
    ["deployments.jobs.containers.methods.getAll", ['v', 'v', 'w']],
    ["deployments.jobs.containers.methods.getAll", ['v', 'v', 1, 'w']],
    ["deployments.jobs.containers.methods.getAll", ['v', 'v', 1, 1, 1]],
    ["deployments.jobs.containers.methods.getAll", ['v', 'v', 1, 1, 'v', 1]],

    ["deployments.jobs.routes.add", [1, {}]],
    ["deployments.jobs.routes.update", [1, 1, {}]],
    ["deployments.jobs.routes.delete", [1, 1]],
    ["deployments.jobs.routes.get", [1, 1]],
    ["deployments.jobs.routes.getAll", [1]],
    ["deployments.jobs.routes.getAll", [1, 1]],
    ["deployments.jobs.routes.getAll", [1, 1, 1]],
    ["deployments.jobs.routes.getAll", [1, 1, 1, "name"]],
    ["deployments.jobs.routes.getAll", [1, 1, 1, "name", 1]],

    ["deployments.jobs.os.add", [1, {}]],
    ["deployments.jobs.os.delete", [1, 1]],
    ["deployments.jobs.os.get", [1, 1]],
    ["deployments.jobs.os.getAll", [1]],
    ["deployments.jobs.os.getAll", [1, 1]],
    ["deployments.jobs.os.getAll", [1, 1, 1]],
    ["deployments.jobs.os.getAll", [1, 1, 1, "name"]],
    ["deployments.jobs.os.getAll", [1, 1, 1, "name", 1]],

    ["deployments.jobs.schedules.create", [1]],
    ["deployments.jobs.schedules.update", [1, "w"]],
    ["deployments.jobs.schedules.delete", [1]],
    ["deployments.jobs.schedules.get", [1]],
    ["deployments.jobs.schedules.getAll", [{}, {}, {}, {}, {}]],

    ["deployments.rollouts.getAll", ['v']],
    ["deployments.rollouts.getAll", [1, 'v']],
    ["deployments.rollouts.getAll", [1, 1, 'v']],
    ["deployments.rollouts.getAll", [1, 1, 1, 1]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", 1]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc", 1]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc", 'v', 1]],
    ["deployments.rollouts.get", [1]],
    ["deployments.rollouts.pause", [1]],
    ["deployments.rollouts.start", [1]],
    ["deployments.rollouts.rollback", [1]],
    ["deployments.rollouts.getRollbacks", [1, "v"]],
    ["deployments.rollouts.getRollbacks", ["v", 1]],
    ["deployments.rollouts.getRollbacks", [1, 1]],
    ["deployments.rollouts.delete", [1]],

    ["softwaremodules.modules.create", ['w']],
    ["softwaremodules.modules.get", ['w']],
    ["softwaremodules.modules.delete", ['w']],
    ["softwaremodules.artifacts.create", ["w", 1]],
    ["softwaremodules.artifacts.get", ["w", "w"]],
    ["softwaremodules.orders.getAll", [{}, {}, {}, {}, {}]],
    ["softwaremodules.orders.get", ["wrong"]],

    ["metrics.query.get", [1]],
    ["metrics.query.getAll", [{}, {}, {}, {}, {}]],
    ["metrics.query.create", ["w"]],
    ["metrics.query.update", [{}, "w"]],
    ["metrics.query.delete", [1]],
    ["metrics.query.execute", [{}, {}, "w"]],
    ["metrics.query.executeSaved", ["w", "w", {}, 1, 1]],
    ["metrics.query.executeSaved", ["w", "w", {}, 1, 1]],
    ["metrics.query.executeSaved", [1, "v", "w", "w", "v"]],
    ["metrics.requestdata.get", [1]],

    ["bugreports.send", ["wrong", {}]],

    ["announcements.getAll", [1]],
    ["announcements.getAll", ['v', 1]],
    ["announcements.getAll", ['v', 'v', 1]],

    ["documentation.getAll", [{}, {}, {}, {}, {}]],
    ["documentation.get", [1, 1]],
    ["documentation.versions.get", [1, 'v', 1]],
    ["documentation.versions.get", ['v', 1, 1]],
    ["documentation.versions.get", [1, 1]],

    ["sessions.update", [1]],
    ["sessions.get", [1]],
    ["sessions.getAll", ['v']],
    ["sessions.getAll", ['v', 'v']],
    ["sessions.getAll", ['v', 'v', 1]],
    ["sessions.getAll", ['v', 'v', 1, 1]],

    ["sessions.getConnectionDevices", ['v']],
    ["sessions.getConnectionDevices", ['v', 'v']],
    ["sessions.getConnectionDevices", ['v', 'v', 1]],
    ["sessions.getConnectionDevices", ['v', 'v', 1, 1]],
    ["sessions.getConnectionDevices", ['v', 'v', 1, 1, 1]],
    ["sessions.getConnectionDevices", ['v', 'v', 1, 1, [1]]],

    ["blocklists.create", ['w']],
    ["blocklists.delete", [1]],
    ["blocklists.update", [1, {}]],
    ["blocklists.get", [1]],
    ["blocklists.getAll", ['v']],
    ["blocklists.getAll", ['v', 'v']],
    ["blocklists.getAll", ['v', 'v', 1]],
    ["blocklists.getAll", ['v', 'v', 1, 1]],

    ["pages.get", [1]],
    ["pages.templates.get", [1, 'v']],
    ["pages.templates.get", ['v', 1]],
    ["pages.templates.get", [1, 1]],
];

describe("Incorrect Input Suite", function () {
    test.each(calls)(
        'sdk.%s with input: %s rejects promise on wrong input',
        async (functionPath, invalidSignature) => {
            expect.assertions(1)
            const sdkFunction = _get(edgeSDK, functionPath);
            return expect(sdkFunction(...invalidSignature)).rejects.toThrow();
        },
    );

    test.each(calls)(
        'sdk.%s with input: %s returns an error in the callback on wrong input',
        async (functionPath, invalidSignature) => {
            const callback = jest.fn()
            const sdkFunction = _get(edgeSDK, functionPath);
            sdkFunction(...invalidSignature, callback);
            expect(callback).toBeCalled();
            expect(typeof callback.mock.calls[0][0]).toBe('object');
            expect(callback.mock.calls[0][1]).toBe(null);
        },
    );
});
