/**********************************************************************
 * Copyright (c) 2021 Hilscher Gesellschaft fuer Systemautomation mbH
 * See LICENSE file
**********************************************************************/

const edgeSDK = require('../src/index');
const _get = require('lodash').get;
jest.mock('../src/client.js');

const suggestInvalid = {
    organisationId: 1,
    search: "valid",
    invalidAttribute: "invalid"
};

const suggestInvalidTwo = {
    organisationId: 1,
    search: 1,
    invalidAttribute: "invalid"
};

const calls = [
    ["devices.customFields.delete", [1, 1]],
    ["devices.notifications.delete", [1, 1]],
    ["devices.customFields.get", [1, 1]],
    ["devices.create", ["wrong"]],
    ["devices.onBoard", ["wrong"]],
    ["devices.notifications.deleteAll", [1]],
    ["devices.delete", [1]],
    ["devices.get", [1]],
    ["devices.offBoard", [1]],
    ["devices.offBoardConfirm", [1]],
    ["devices.create", ["w"]],
    ["devices.getAll", [{}, {}, {}, {}, {}, {}]],
    ["devices.getStatusList", [[1, 1]]],
    ["devices.methods", [1, 1]],
    ["devices.update", [1, 1]],
    ["devices.onBoard", [1]],
    ["devices.onboardSesnorEdge", [1]],
    ["devices.enableDisable", [1, "w", 1]],
    ["devices.customFields.create", [1, 1]],
    ["devices.customFields.update", [1, 1, 1]],
    ["devices.notifications.create", [1, 1]],
    ["devices.notifications.getAll", ["w", 1, "w", "w", "w"]],
    ["devices.customFields.getAll", ["w", 1, "w", "w", "w"]],
    ["devices.containers.routes.delete", [1, 1]],
    ["devices.containers.routes.create", [1, 1]],
    ["devices.containers.routes.update", [1, 1, 1]],
    ["devices.containers.routes.getAll", [1]],
    ["devices.containers.routes.get", ["valid", 1]],
    ["devices.containers.routes.get", [1, "valid"]],
    ["devices.containers.routes.get", [1, 1]],
    ["devices.containers.get", ["valid", 1]],
    ["devices.containers.get", [1, "valid"]],
    ["devices.containers.getInstalled", [1]],
    ["devices.containers.getInstalled", [1, "w", "w", 1, 1, 1]],
    ["devices.containers.getDeployable", [1]],
    ["devices.containers.delete", [1, "valid"]],
    ["devices.containers.create", [1, "valid", {}]],
    ["devices.containers.update", [1, "valid", {}]],
    ["devices.containers.properties", [1, "valid"]],
    ["devices.containers.deleteAll", [1]],
    ["devices.remote.create", [1, {}]],
    ["devices.remote.create", ["valid", "valid"]],
    ["devices.remote.status", [1]],
    ["devices.remote.credentials", [1]],
    ["devices.deploymentManifests.check", [1]],
    ["devices.deploymentManifests.check", [{}]],
    ["devices.deploymentManifests.deploy", [1]],
    ["devices.deploymentManifests.deploy", [{}]],

    ["dashboards.create", ["w"]],
    ["dashboards.update", [1, "w"]],
    ["dashboards.get", [1]],
    ["dashboards.getAll", [{}]],
    ["dashboards.delete", [1]],
    ["dashboards.panels.create", [1, "w"]],
    ["dashboards.panels.update", [1, 1, "w"]],
    ["dashboards.panels.get", [1, 1]],
    ["dashboards.panels.getAll", [1]],
    ["dashboards.panels.delete", [1, 1]],
    ["dashboards.series.create", [1, 1, "w"]],
    ["dashboards.series.update", [1, 1, 1, "w"]],
    ["dashboards.series.get", [1, 1, 1]],
    ["dashboards.series.getAll", [1, 1]],
    ["dashboards.series.delete", [1, 1, 1]],

    ["containers.create", ["wrong"]],
    ["containers.delete", [1]],
    ["containers.delete", [1, "w"]],
    ["containers.get", [1]],
    ["containers.update", [1, 1]],
    ["containers.update", [1, 1]],
    ["containers.share", [1, ["v"]]],
    ["containers.share", [1, 1]],
    ["containers.unshare", [1, "v"]],
    ["containers.getAll", ["w", "w"]],
    ["containers.getAll", [1, "w"]],
    ["containers.getAll", [1, 1, 1]],
    ["containers.getAll", [1, 1, "w", 1]],
    ["containers.getAll", [1, 1, "w", 1, "w"]],
    ["containers.versions.createversion", ["w", {}]],
    ["containers.versions.deleteversion", [1, 1]],
    ["containers.versions.getversion", [1, 1]],
    ["containers.versions.getallversions", [1]],
    ["containers.versions.getallversions", [1, 1]],
    ["containers.versions.getallversions", [1, 1, 1]],
    ["containers.versions.getallversions", [1, 1, 1, "name"]],
    ["containers.versions.getallversions", [1, 1, 1, "name", 1]],
    ["containers.versions.updateversion", ["w", "v", "v"]],
    ["containers.disable", [1, "w"]],

    ["sensoredgemanifest.create", ["wrong"]],
    ["sensoredgemanifest.delete", [1]],
    ["sensoredgemanifest.get", [1]],
    ["sensoredgemanifest.update", [1, 1]],
    ["sensoredgemanifest.update", [1, 1]],
    ["sensoredgemanifest.getAll", ["w", "w"]],
    ["sensoredgemanifest.getAll", [1, "w"]],
    ["sensoredgemanifest.getAll", [1, 1, 1]],
    ["sensoredgemanifest.getAll", [1, 1, "w", 1]],
    ["sensoredgemanifest.uploadOs", ["w"]],
    ["sensoredgemanifest.uploadOs", [1]],

    ["users.createself", ["wrong"]],
    ["users.create", ["wrong"]],
    ["users.sensoredge.create", ["wrong"]],
    ["users.profile.update", ["wrong"]],
    ["users.profile.notificationEmails.add", ["wrong"]],
    ["users.profile.notificationEmails.add", [1]],
    ["users.profile.notificationEmails.getAll", ['w']],
    ["users.profile.notificationEmails.getAll", [1, 'w']],
    ["users.profile.notificationEmails.getAll", [1, 1, 1]],
    ["users.profile.notificationEmails.getAll", [1, 1, 'v', 1]],
    ["users.profile.notificationEmails.delete", ['w']],
    ["users.profile.notificationEmails.delete", [{}]],
    ["users.verifyusers", ["wrong"]],
    ["users.sensoredge.verify", ["wrong"]],
    ["users.sensoredge.getverify", [1]],
    ["users.sensoredge.getverify", [undefined]],
    ["users.getAll", [{}, {}, {}, {}, {}]],
    ["users.get", ["wrong"]],
    ["users.getverify", [1]],
    ["users.getverify", [undefined]],
    ["users.update", ["wrong", "wrong"]],
    ["users.sensoredge.completeRegistration", ["wrong"]],
    ["users.delete", ["wrong"]],
    ["users.roles.add", [{}, {}]],
    ["users.roles.delete", [{}, {}]],
    ["users.roles.getAll", [{}, {}, {}, {}, {}]],
    ["users.suggest", [suggestInvalid]],
    ["users.suggest", [suggestInvalidTwo]],

    ["keys.create", ["wrong"]],
    ["keys.delete", [1]],
    ["keys.get", [1]],
    ["keys.update", [1, 1]],
    ["keys.getAll", [{}, {}, {}, {}, {}]],
    ["keys.createSensorEdgeKey", ["w"]],

    ["auth.resetPassword", [1]],
    ["auth.setPassword", [1]],

    ["organisation.get", ["w", "w"]],
    ["organisation.get", ["w"]],
    ["organisation.update", ["w", "w"]],
    ["organisation.create", ["w", "w"]],
    ["organisation.delete", ["w"]],
    ["organisation.getAll", ["w", "w"]],
    ["organisation.getAll", [1, "w"]],
    ["organisation.getAll", [1, 1, 1]],
    ["organisation.getAll", [1, 1, "w", 1]],
    ["organisation.getAll", [1, 1, "w", 'w', 1]],

    ["organisation.manifest.createContainer", ["w", 1, {}]],
    ["organisation.manifest.createRoute", ["w", {}]],
    ["organisation.manifest.getContainers", ["w"]],
    ["organisation.manifest.getRoutes", ["w"]],
    ["organisation.manifest.deleteContainer", ["w", 1]],
    ["organisation.manifest.deleteRoute", ["w", 1]],
    ["organisation.manifest.updateContainer", ["w", 1, {}]],
    ["organisation.manifest.updateRoute", ["w", 1, {}]],
    ["organisation.manifest.getContainer", ["w", 1]],
    ["organisation.manifest.getRoute", [1, 1]],
    ["organisation.manifest.getContainers", ["w"]],
    ["organisation.manifest.getContainers", [1, "w"]],
    ["organisation.manifest.getContainers", [1, "w", "w"]],
    ["organisation.manifest.getContainers", [1, 1, 1, 1]],
    ["organisation.manifest.getContainers", [1, 1, 1, 1, 1]],
    ["organisation.manifest.getRoutes", ["w"]],
    ["organisation.manifest.getRoutes", [1, "w"]],
    ["organisation.manifest.getRoutes", [1, "w", "w"]],
    ["organisation.manifest.getRoutes", [1, 1, 1, 1]],
    ["organisation.manifest.getRoutes", [1, 1, 1, 1, 1]],
    ["organisation.manifest.copyManifest", ["w"]],
    ["organisation.manifest.applyManifest", ['invalid', 1]],

    ["roles.create", ["w", "w"]],
    ["roles.get", [{}, {}]],
    ["roles.update", ["w", {}, 1]],
    ["roles.getAll", [{}, {}, {}, {}, {}]],
    ["roles.delete", [{}, {}]],

    ["search.devices", [1]],
    ["search.devices", ["v", 1]],
    ["search.devices", ["v", [1]]],
    ["search.devices", ["v", "v", 1]],
    ["search.devices", ["v", "v", "fuzzy", "w"]],
    ["search.devices", ["v", "v", "fuzzy", 1, "w"]],
    ["search.devices", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.devices", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.containers", [1]],
    ["search.containers", ["v", 1]],
    ["search.containers", ["v", [1]]],
    ["search.containers", ["v", "v", 1]],
    ["search.containers", ["v", "v", "fuzzy", "w"]],
    ["search.containers", ["v", "v", "fuzzy", 1, "w"]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 1, "v"]],
    ["search.organisations", [1]],
    ["search.organisations", ["v", 1]],
    ["search.organisations", ["v", [1]]],
    ["search.organisations", ["v", "v", 1]],
    ["search.organisations", ["v", "v", "fuzzy", "w"]],
    ["search.organisations", ["v", "v", "fuzzy", 1, "w"]],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.users", [1]],
    ["search.users", ["v", 1]],
    ["search.users", ["v", [1]]],
    ["search.users", ["v", "v", 1]],
    ["search.users", ["v", "v", "fuzzy", "w"]],
    ["search.users", ["v", "v", "fuzzy", 1, "w"]],
    ["search.users", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.users", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.deploymentFilters", [1]],
    ["search.deploymentFilters", ["v", 1]],
    ["search.deploymentFilters", ["v", [1]]],
    ["search.deploymentFilters", ["v", "v", 1]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", "w"]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, "w"]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.deploymentJobs", [1]],
    ["search.deploymentJobs", ["v", 1]],
    ["search.deploymentJobs", ["v", [1]]],
    ["search.deploymentJobs", ["v", "v", 1]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", "w"]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, "w"]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1, 'name', 1]],
    ["search.deploymentRollouts", ["v", 1]],
    ["search.deploymentRollouts", ["v", [1]]],
    ["search.deploymentRollouts", ["v", "v", 1]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", "w"]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, "w"]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1, 1]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1, 'name', 1]],


    ["permissions.devices", [[1, 1, 1]]],
    ["permissions.containers", [[1, 1, 1]]],
    ["permissions.organisations", [["v", "v"]]],
    ["permissions.users", [["v", "v"]]],
    ["permissions.roles", [1]],
    ["permissions.tenants", [["v", "v"]]],
    ["permissions.keys", [[1, 1, 1]]],
    ["permissions.edgeos", [[1, 1, 1]]],
    ["permissions.webhooks", [[1, 1, 1]]],
    ["permissions.groups", [["v", "v"]]],

    ["permissions.devices", [1]],
    ["permissions.containers", [1]],
    ["permissions.organisations", [1]],
    ["permissions.users", [1]],
    ["permissions.tenants", [1]],
    ["permissions.keys", [1]],
    ["permissions.edgeos", [1]],
    ["permissions.permissions", [1]],
    ["permissions.webhooks", [1]],
    ["permissions.groups", ["v"]],

    ["edgeos.getAll", [{}, {}, {}, {}, {}, {}]],
    ["edgeos.create", [1]],
    ["edgeos.update", [1, 1]],
    ["edgeos.get", [1]],
    ["edgeos.delete", [1]],

    ["tenants.create", ["wrong"]],
    ["tenants.update", ["w", "w"]],
    ["tenants.get", ["w"]],
    ["tenants.getAll", [{}, {}, {}, {}]],
    ["tenants.delete", ["w"]],

    ["webhooks.create", ["w"]],
    ["webhooks.test", ["w"]],
    ["webhooks.test", [1]],
    ["webhooks.delete", [1]],
    ["webhooks.get", [1]],
    ["webhooks.update", [1, {}]],
    ["webhooks.update", [1, 'w']],
    ["webhooks.getAll", ['w']],
    ["webhooks.getAll", [1, 'w']],
    ["webhooks.getAll", [1, 'v', 'v']],
    ["webhooks.getAll", ["w"]],
    ["webhooks.getAll", [1, "w"]],
    ["webhooks.getAll", [1, "w", "w"]],
    ["webhooks.getAll", [1, 1, 1, 1]],
    ["webhooks.getAll", [1, 1, 1, 1, 1]],

    ["groups.get", ["w", "w"]],
    ["groups.get", ["w"]],
    ["groups.update", ["w", "w"]],
    ["groups.create", ["w", "w"]],
    ["groups.delete", ["w"]],
    ["groups.getGroupItems", ["w"], ["w"], ["w"], [1], [1], ["w"]],
    ["groups.addDevice", ["w", 1]],
    ["groups.removeDevice", ["w", 1]],
    ["groups.addContainer", ["w", 1]],
    ["groups.removeContainer", ["w", 1]],

    ["deployments.filters.create", [1]],
    ["deployments.filters.create", ["w"]],
    ["deployments.filters.getAll", [{}, {}, {}, {}, {}]],
    ["deployments.filters.update", [1, "w"]],
    ["deployments.filters.delete", [1]],
    ["deployments.filters.get", [1]],
    ["deployments.filters.execute", [1]],
    ["deployments.filters.execute", [{}, 'w']],
    ["deployments.filters.execute", [{}, 1, 'w']],
    ["deployments.filters.execute", [{}, 1, 1, 1]],
    ["deployments.filters.execute", [{}, 1, 1, "v", 1]],

    ["deployments.jobs.create", [1]],
    ["deployments.jobs.update", [1, "w"]],
    ["deployments.jobs.delete", [1]],
    ["deployments.jobs.get", [1]],
    ["deployments.jobs.getAll", [{}, {}, {}, {}, {}]],
    ["deployments.jobs.execute", [1, 'v']],
    ["deployments.jobs.execute", ['v', 1]],
    ["deployments.jobs.execute", ['v', 'v', 'v']],

    ["deployments.jobs.containers.add", [1, 1, {}]],
    ["deployments.jobs.containers.update", [1, 1, {}]],
    ["deployments.jobs.containers.delete", [1, 1]],
    ["deployments.jobs.containers.get", [1, 1]],
    ["deployments.jobs.containers.getAll", [1]],
    ["deployments.jobs.containers.getAll", [1, 1]],
    ["deployments.jobs.containers.getAll", [1, 1, 1]],
    ["deployments.jobs.containers.getAll", [1, 1, 1, "name"]],
    ["deployments.jobs.containers.getAll", [1, 1, 1, "name", 1]],

    ["deployments.jobs.containers.methods.add", [1, 'v', {}]],
    ["deployments.jobs.containers.methods.add", ['v', 1, {}]],
    ["deployments.jobs.containers.methods.update", [1, 'v', 'v', {}]],
    ["deployments.jobs.containers.methods.update", ['v', 1, 'v', {}]],
    ["deployments.jobs.containers.methods.update", ['v', 'v', 1, {}]],
    ["deployments.jobs.containers.methods.delete", [1, 'v', 'v']],
    ["deployments.jobs.containers.methods.delete", ['v', 1, 'v']],
    ["deployments.jobs.containers.methods.delete", ['v', 'v', 1]],
    ["deployments.jobs.containers.methods.get", [1, 'v', 'v']],
    ["deployments.jobs.containers.methods.get", ['v', 1, 'v']],
    ["deployments.jobs.containers.methods.get", ['v', 'v', 1]],
    ["deployments.jobs.containers.methods.getAll", [1, 'v']],
    ["deployments.jobs.containers.methods.getAll", ['v', 1]],
    ["deployments.jobs.containers.methods.getAll", ['v', 'v', 'w']],
    ["deployments.jobs.containers.methods.getAll", ['v', 'v', 1, 'w']],
    ["deployments.jobs.containers.methods.getAll", ['v', 'v', 1, 1, 1]],
    ["deployments.jobs.containers.methods.getAll", ['v', 'v', 1, 1, 'v', 1]],

    ["deployments.jobs.routes.add", [1, {}]],
    ["deployments.jobs.routes.update", [1, 1, {}]],
    ["deployments.jobs.routes.delete", [1, 1]],
    ["deployments.jobs.routes.get", [1, 1]],
    ["deployments.jobs.routes.getAll", [1]],
    ["deployments.jobs.routes.getAll", [1, 1]],
    ["deployments.jobs.routes.getAll", [1, 1, 1]],
    ["deployments.jobs.routes.getAll", [1, 1, 1, "name"]],
    ["deployments.jobs.routes.getAll", [1, 1, 1, "name", 1]],

    ["deployments.rollouts.getAll", ['v']],
    ["deployments.rollouts.getAll", [1, 'v']],
    ["deployments.rollouts.getAll", [1, 1, 'v']],
    ["deployments.rollouts.getAll", [1, 1, 1, 1]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", 1]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc", 1]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc", 'v', 1]],
    ["deployments.rollouts.get", [1]],
    ["deployments.rollouts.pause", [1]],
    ["deployments.rollouts.start", [1]],
    ["deployments.rollouts.rollback", [1]],
    ["deployments.rollouts.getRollbacks", [1, "v"]],
    ["deployments.rollouts.getRollbacks", ["v", 1]],
    ["deployments.rollouts.getRollbacks", [1, 1]],

    ["softwaremodules.modules.create", ['w']],
    ["softwaremodules.modules.get", ['w']],
    ["softwaremodules.artifacts.create", ["w", 1]],
    ["softwaremodules.artifacts.get", ["w", "w"]],
    ["softwaremodules.orders.getAll", [{}, {}, {}, {}, {}]],
    ["softwaremodules.orders.get", ["wrong"]],
];

describe("Incorrect Input Suite", function () {
    test.each(calls)(
        'sdk.%s with input: %s rejects promise on wrong input',
        async (functionPath, invalidSignature) => {
            expect.assertions(1)
            const sdkFunction = _get(edgeSDK, functionPath);
            return expect(sdkFunction(...invalidSignature)).rejects.toThrow();
        },
    );

    test.each(calls)(
        'sdk.%s with input: %s returns an error in the callback on wrong input',
        async (functionPath, invalidSignature) => {
            const callback = jest.fn()
            const sdkFunction = _get(edgeSDK, functionPath);
            sdkFunction(...invalidSignature, callback);
            expect(callback).toBeCalled();
            expect(typeof callback.mock.calls[0][0]).toBe('object');
            expect(callback.mock.calls[0][1]).toBe(null);
        },
    );
});
