/**********************************************************************
 * Copyright (c) 2022 Hilscher Gesellschaft fuer Systemautomation mbH
 * See LICENSE file
 **********************************************************************/
const FormData = require('form-data');
const edgeSDK = require('../src/index');
const _get = require('lodash').get;
jest.mock('../src/client.js');

const suggestValid = {
    organisationId: 1,
    search: "valid",
};

const suggestValidTwo = {
    search: "valid",
};

const calls = [
    ["devices.customFields.delete", ["valid", "valid"]],
    ["devices.notifications.delete", ["valid", "valid"]],
    ["devices.customFields.get", ["valid", "valid"]],
    ["devices.create", [{}]],
    ["devices.onBoard", [{}]],
    ["devices.onBoardWithKey", [{}]],
    ["devices.notifications.deleteAll", ["valid"]],
    ["devices.delete", ["valid"]],
    ["devices.get", ["valid"]],
    ["devices.getWithKey", ["valid"]],
    ["devices.getChildren", ["valid"]],
    ["devices.offBoard", ["valid"]],
    ["devices.offBoardConfirm", [{}]],
    ["devices.offBoardConfirm", [{}, 'v']],
    ["devices.create", [{}]],
    ["devices.getAll", [1]],
    ["devices.getAll", [1, 1]],
    ["devices.getAll", [1, 1, 1]],
    ["devices.getAll", [1, 1, 1, "name"]],
    ["devices.getAll", [1, 1, 1, "name", "asc"]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid"]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid", []]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid", "v"]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid", [], []]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid", [], "v"]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid", [], "v", "None"]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid", [], "v", []]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid", [], [], []]],
    ["devices.getWithGeolocation", [1]],
    ["devices.getWithGeolocation", [1, "standard"]],
    ["devices.getWithGeolocation", [1, "standard", "name"]],
    ["devices.getWithGeolocation", [1, "standard", "name", "asc"]],
    ["devices.getStatusList", [
        ["w", "w"]
    ]],
    ["devices.methods", ["w", {}]],
    ["devices.update", ["w", {}]],
    ["devices.onBoard", [{}]],
    ["devices.onBoardWithKey", [{}]],
    ["devices.onboardSensorEdge", [{}]],
    ["devices.filter", [{}]],
    ["devices.enableDisable", ["v", true, {}]],
    ["devices.enableDisable", ["v", false, {}]],
    ["devices.customFields.create", ["w", {}]],
    ["devices.customFields.update", ["v", "v", {}]],
    ["devices.notifications.create", ["v", {}]],
    ["devices.notifications.getAll", ["w"]],
    ["devices.notifications.getAll", ["w", 1]],
    ["devices.notifications.getAll", ["w", 1, 1]],
    ["devices.notifications.getAll", ["w", 1, 1, "w"]],
    ["devices.notifications.getAll", ["w", 1, 1, "w", "w"]],
    ["devices.customFields.getAll", ["w"]],
    ["devices.customFields.getAll", ["w", 1]],
    ["devices.customFields.getAll", ["w", 1, 1]],
    ["devices.customFields.getAll", ["w", 1, 1, "w"]],
    ["devices.customFields.getAll", ["w", 1, 1, "w", "w"]],
    ["devices.containers.routes.create", ["v", {}]],
    ["devices.containers.routes.update", ["v", "v", {}]],
    ["devices.containers.routes.getAll", ["valid"]],
    ["devices.containers.routes.get", ["valid", "valid"]],
    ["devices.containers.routes.delete", ["valid", "valid"]],
    ["devices.containers.get", ["valid", "valid"]],
    ["devices.containers.getSystem", ["valid", "valid"]],
    ["devices.containers.getInstalled", ["valid"]],
    ["devices.containers.getInstalled", ["w", 1]],
    ["devices.containers.getInstalled", ["w", 1, 1]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w"]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w", "w"]],
    ["devices.containers.getSystemInstalled", ["valid"]],
    ["devices.containers.getSystemInstalled", ["w", 1]],
    ["devices.containers.getSystemInstalled", ["w", 1, 1]],
    ["devices.containers.getSystemInstalled", ["w", 1, 1, "w"]],
    ["devices.containers.getSystemInstalled", ["w", 1, 1, "w", "w"]],
    ["devices.containers.getDevicesPlatforms", ['v']],
    ["devices.containers.getDevicesPlatforms", [['v', 'v']]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w", "w", "all"]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w", "w", "all", []]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w", "w", "all", "w"]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w", "w", "all", "w", []]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w", "w", "all", "w", "w"]],
    ["devices.containers.getDeployable", ["valid"]],
    ["devices.containers.getDeployable", ["w", 1]],
    ["devices.containers.getDeployable", ["w", 1, 1]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w"]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w"]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w", false]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w", false, []]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w", false, 'v']],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w", false, [], []]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w", false, [], 'v']],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w", false, [], [], true]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w", false, [], [], false]],
    ["devices.containers.delete", ["valid", "valid"]],
    ["devices.containers.create", ["valid", "valid", {}]],
    ["devices.containers.update", ["valid", "valid", {}]],
    ["devices.containers.properties", ["valid", "valid"]],
    ["devices.containers.deleteAll", ["v"]],
    ["devices.containers.deleteDeviceContainers", ["v", "v"]],
    ["devices.containers.getdeployableversions", ["v", "v"]],
    ["devices.containers.createList", ["v", {}]],
    ["devices.containers.updateList", ["v", {}]],
    ["devices.remote.create", ["valid", {}]],
    ["devices.remote.status", ["valid"]],
    ["devices.remote.credentials", ["valid"]],
    ["devices.deploymentManifests.check", ["valid"]],
    ["devices.deploymentManifests.deploy", ["valid"]],
    ["devices.messages.getAll", ["v", new Date(), new Date()]],
    ["devices.messages.getAll", ["v", new Date(), new Date(), "v"]],
    ["devices.messages.getAll", ["v", new Date(), new Date(), "v", "v"]],
    ["devices.messages.getAll", ["v", new Date(), new Date(), "v", "v", 1]],
    ["devices.topics.getAll", ["v", new Date(), new Date()]],

    ["dashboards.create", [{}]],
    ["dashboards.update", ["v", {}]],
    ["dashboards.get", ["v"]],
    ["dashboards.getAll", [1]],
    ["dashboards.getAll", [1, 1]],
    ["dashboards.getAll", [1, 1, 1]],
    ["dashboards.getAll", [1, 1, 1, "name"]],
    ["dashboards.getAll", [1, 1, 1, "name", "asc"]],
    ["dashboards.delete", ["v"]],
    ["dashboards.panels.create", ["v", {}]],
    ["dashboards.panels.update", ["v", "v", {}]],
    ["dashboards.panels.get", ["v", "v"]],
    ["dashboards.panels.getAll", ["v"]],
    ["dashboards.panels.delete", ["v", "v"]],
    ["dashboards.series.create", ["v", "v", {}]],
    ["dashboards.series.update", ["v", "v", "v", {}]],
    ["dashboards.series.get", ["v", "v", "v"]],
    ["dashboards.series.getAll", ["v", "v"]],
    ["dashboards.series.delete", ["v", "v", "v"]],

    ["containers.create", [{}]],
    ["containers.delete", ["valid"]],
    ["containers.delete", ["valid", true]],
    ["containers.delete", ["valid", false]],
    ["containers.get", ["valid"]],
    ["containers.update", ["v", {}]],
    ["containers.update", ["v", {}]],
    ["containers.getAll", []],
    ["containers.getAll", [1, 1, "name", "asc", true]],
    ["containers.getAll", [1, 1, "name", "asc", false]],
    ["containers.getAll", [1, 1, "name", "asc", false, []]],
    ["containers.getAll", [1, 1, "name", "asc", false, 'v']],
    ["containers.getAll", [1, 1, "name", "asc", false, [], []]],
    ["containers.getAll", [1, 1, "name", "asc", false, [], 'v']],
    ["containers.getAll", [1, 1, "name", "asc", false, [], [], true]],
    ["containers.getAll", [1, 1, "name", "asc", false, [], [], false]],
    ["containers.sharings.share", [{}]],
    ["containers.sharings.unshare", [1]],
    ["containers.sharings.get", [1]],
    ["containers.sharings.getAll", ["v"]],
    ["containers.sharings.getAll", ["v", 1]],
    ["containers.sharings.getAll", ["v", 1, 1]],
    ["containers.sharings.getAll", ["v", 1, 1, "v"]],
    ["containers.sharings.getAll", ["v", 1, 1, "v", "asc"]],
    ["containers.sharings.update", [1, {}]],
    ["containers.versions.sharings.unshare", [1, {}]],
    ["containers.versions.createversion", [{}, "v"]],
    ["containers.versions.deleteversion", ["v", "v"]],
    ["containers.versions.getversion", ["v", "v"]],
    ["containers.versions.getallversions", ["v"]],
    ["containers.versions.getallversions", ["v", 1]],
    ["containers.versions.getallversions", ["v", 1, 1]],
    ["containers.versions.getallversions", ["v", 1, 1, "name"]],
    ["containers.versions.updateversion", [{}, "v", "v"]],
    ["containers.disable", ["v", {}]],
    ["containers.envVariables.getAll", ['v']],
    ["containers.envVariables.getAll", ['v', 'v']],

    ["users.createself", [{}, 'v']],
    ["users.create", [{}]],
    ["users.sensoredge.create", [{}]],
    ["users.sensoredge.create", [{}, 'v']],
    ["users.profile.update", [{}]],
    ["users.profile.notificationEmails.add", [{}]],
    ["users.profile.notificationEmails.getAll", []],
    ["users.profile.notificationEmails.getAll", [1]],
    ["users.profile.notificationEmails.getAll", [1, 1]],
    ["users.profile.notificationEmails.getAll", [1, 1, 'v']],
    ["users.profile.notificationEmails.getAll", [1, 1, 'v', 'asc']],
    ["users.profile.notificationEmails.delete", [1]],
    ["users.profile.notificationEmails.delete", [1, 'v']],
    ["users.verifyusers", [{}]],
    ["users.verifyusers", [{}, 'v']],
    ["users.sensoredge.verify", [{}]],
    ["users.sensoredge.verify", [{}, 'v']],
    ["users.sensoredge.getverify", ["v"]],
    ["users.sensoredge.getverify", ["v", 'v']],
    ["users.sensoredge.getverify", ["v", 'v']],
    ["users.getAll", [1]],
    ["users.getAll", [1, 1]],
    ["users.getAll", [1, 1, 1]],
    ["users.getAll", [1, 1, 1, "name"]],
    ["users.getAll", [1, 1, 1, "name", "asc"]],
    ["users.get", [1, 1]],
    ["users.getverify", ["valid"]],
    ["users.getverify", ["valid", 'v']],
    ["users.getverify", ["valid", 'v', 'v']],
    ["users.update", [1, {}]],
    ["users.sensoredge.completeRegistration", [{}]],
    ["users.sensoredge.completeRegistration", [{}, 'v']],
    ["users.delete", [1]],
    ["users.roles.add", [1, "valid", 1]],
    ["users.roles.delete", [1, 1, "valid"]],
    ["users.roles.getAll", [1, 1]],
    ["users.roles.getAll", [1, 1, 1]],
    ["users.roles.getAll", [1, 1, 1, 1]],
    ["users.roles.getAll", [1, 1, 1, 1, "name"]],
    ["users.roles.getAll", [1, 1, 1, 1, "name", "asc"]],
    ["users.suggest", [suggestValid]],
    ["users.suggest", [suggestValidTwo]],
    ["users.invite.create", [{}]],
    ["users.invite.update", [{}]],
    ["users.invite.update", [{}, 'v']],
    ["users.invite.getAll", [1]],
    ["users.invite.getAll", [1, 1]],
    ["users.invite.getAll", [1, 1, 1]],
    ["users.invite.getAll", [1, 1, 1, "name"]],
    ["users.invite.getAll", [1, 1, 1, "name", "asc"]],
    ["users.invite.revoke", [1, {}]],
    ["users.invite.delete", [1]],
    ["users.workspaces.getAll", [1]],
    ["users.workspaces.getAll", [1, 1]],
    ["users.workspaces.getAll", [1, 1, 1]],
    ["users.workspaces.getAll", [1, 1, 1, "name"]],
    ["users.workspaces.getAll", [1, 1, 1, "name", "asc"]],
    ["users.workspaces.delete", [1, 1]],
    ["users.preferences.update", [{}]],

    ["keys.create", [{}]],
    ["keys.delete", ["valid"]],
    ["keys.get", ["valid"]],
    ["keys.update", ["v", {}]],
    ["keys.getAll", [1]],
    ["keys.getAll", [1, 1]],
    ["keys.getAll", [1, 1, 1]],
    ["keys.getAll", [1, 1, 1, "v"]],
    ["keys.getAll", [1, 1, 1, "v", "v"]],
    ["keys.createSensorEdgeKey", [{}]],

    ["keys.getConnectionInfo", []],

    ["keys.getConnectionDevices", [1]],
    ["keys.getConnectionDevices", [1, 1]],
    ["keys.getConnectionDevices", [1, 1, "name"]],
    ["keys.getConnectionDevices", [1, 1, "name", "asc"]],
    ["keys.getConnectionDevices", [1, 1, "name", "asc", []]],
    ["keys.getConnectionDevices", [1, 1, "name", "asc", ["deviceid"]]],

    ["auth.resetPassword", ["valid"]],
    ["auth.resetPassword", ["valid", 'v']],
    ["auth.resetPassword", ["valid", 'v', 'v']],
    ["auth.setPassword", [{}]],
    ["auth.setPassword", [{}, 'v']],
    ["auth.sso", [{}]],
    ["auth.twoFactor.enable", []],
    ["auth.twoFactor.disable", ['v']],
    ["auth.twoFactor.verify", [1, 'v']],
    ["auth.twoFactor.send", []],
    ["auth.twoFactor.methods.add", ['v']],
    ["auth.twoFactor.methods.delete", [1, 'v']],
    ["auth.twoFactor.methods.getAll", []],
    ["auth.twoFactor.methods.getEnabled", []],
    ["auth.twoFactor.methods.select", [1]],
    ["auth.twoFactor.methods.verify", [1, 'v']],

    ["organisation.get", [1, 1]],
    ["organisation.get", [1]],
    ["organisation.getAll", []],
    ["organisation.getAll", [1]],
    ["organisation.getAll", [1, 1, 'v']],
    ["organisation.getAll", [1, 1, 'v', 'v']],
    ["organisation.getAll", [1, 1, 'v', 'v', 'v']],
    ["organisation.update", [1, {}]],
    ["organisation.create", [1, {}]],
    ["organisation.delete", [1]],
    ["organisation.createUpgradeRequest", [1, {}]],

    ["organisation.manifest.create", [1, {}]],
    ["organisation.manifest.update", [1, 'v', {}]],
    ["organisation.manifest.delete", [1, 'v']],
    ["organisation.manifest.get", [1, 'v']],
    ["organisation.manifest.getAll", [1]],
    ["organisation.manifest.getAll", [1, 1]],
    ["organisation.manifest.getAll", [1, 1, 1]],
    ["organisation.manifest.getAll", [1, 1, 1, 'v']],
    ["organisation.manifest.getAll", [1, 1, 1, 'v', 'v']],

    ["organisation.manifest.copyManifest", [1]],
    ["organisation.manifest.applyManifest", [1, 'v', 'v']],
    ["organisation.manifest.applyManifest", [1, 'v', 'v', {}]],

    ["organisation.manifest.containers.add", [1, 'v', "v", {}]],
    ["organisation.manifest.containers.update", [1, "v", 'v', {}]],
    ["organisation.manifest.containers.delete", [1, 'v', "v"]],
    ["organisation.manifest.containers.get", [1, "v", 'v']],
    ["organisation.manifest.containers.getAll", [1, 'v']],

    ["organisation.manifest.routes.add", [1, 'v', {}]],
    ["organisation.manifest.routes.update", [1, 'v', 'v', {}]],
    ["organisation.manifest.routes.delete", [1, 'v', 'v']],
    ["organisation.manifest.routes.get", [1, 'v', 'v']],
    ["organisation.manifest.routes.getAll", [1, 'v']],

    ["roles.create", [1, {}]],
    ["roles.get", [1, "v"]],
    ["roles.update", [1, "v", {}]],
    ["roles.getAll", [1]],
    ["roles.getAll", [1, 1]],
    ["roles.getAll", [1, 1, 1]],
    ["roles.getAll", [1, 1, 1, "name"]],
    ["roles.getAll", [1, 1, 1, "name", "asc"]],
    ["roles.delete", [1, "v"]],

    ["search.devices", ["v"]],
    ["search.devices", ["v", "v"]],
    ["search.devices", ["v", ["v"]]],
    ["search.devices", ["v", "v", "fuzzy"]],
    ["search.devices", ["v", "v", "fuzzy", 1]],
    ["search.devices", ["v", "v", "fuzzy", 1, 1]],
    ["search.devices", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.devices", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.containers", ["v"]],
    ["search.containers", ["v", "v"]],
    ["search.containers", ["v", ["v"]]],
    ["search.containers", ["v", "v", "fuzzy"]],
    ["search.containers", ["v", "v", "fuzzy", 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 'asc', true]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 'asc', false]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 'asc', false, 'v']],
    ["search.users", ["v"]],
    ["search.users", ["v", "v"]],
    ["search.users", ["v", ["v"]]],
    ["search.users", ["v", "v", "fuzzy"]],
    ["search.users", ["v", "v", "fuzzy", 1]],
    ["search.users", ["v", "v", "fuzzy", 1, 1]],
    ["search.users", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.users", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.organisations", ["v"]],
    ["search.organisations", ["v", "v"]],
    ["search.organisations", ["v", ["v"]]],
    ["search.organisations", ["v", "v", "fuzzy"]],
    ["search.organisations", ["v", "v", "fuzzy", 1]],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1]],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.deploymentFilters", ["v"]],
    ["search.deploymentFilters", ["v", "v"]],
    ["search.deploymentFilters", ["v", ["v"]]],
    ["search.deploymentFilters", ["v", "v", "fuzzy"]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.deploymentJobs", ["v"]],
    ["search.deploymentJobs", ["v", "v"]],
    ["search.deploymentJobs", ["v", ["v"]]],
    ["search.deploymentJobs", ["v", "v", "fuzzy"]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.deploymentRollouts", ["v"]],
    ["search.deploymentRollouts", ["v", "v"]],
    ["search.deploymentRollouts", ["v", ["v"]]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy"]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1, 'jobName']],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1, 'jobName', 'asc']],
    ["search.tenants", ["v"]],
    ["search.tenants", ["v", "v"]],
    ["search.tenants", ["v", ["v"]]],
    ["search.tenants", ["v", "v", "fuzzy"]],
    ["search.tenants", ["v", "v", "fuzzy", 1]],
    ["search.tenants", ["v", "v", "fuzzy", 1, 1]],
    ["search.tenants", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.tenants", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.keys", ["v"]],
    ["search.keys", ["v", "v"]],
    ["search.keys", ["v", ["v"]]],
    ["search.keys", ["v", "v", "fuzzy"]],
    ["search.keys", ["v", "v", "fuzzy", 1]],
    ["search.keys", ["v", "v", "fuzzy", 1, 1]],
    ["search.keys", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.keys", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.groups", ["v"]],
    ["search.groups", ["v", "v"]],
    ["search.groups", ["v", ["v"]]],
    ["search.groups", ["v", "v", "fuzzy"]],
    ["search.groups", ["v", "v", "fuzzy", 1]],
    ["search.groups", ["v", "v", "fuzzy", 1, 1]],
    ["search.groups", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.groups", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.groups", ["v", "v", "fuzzy", 1, 1, 'name', 'devices']],


    ["permissions.devices", [
        { deviceIds: ["v"] }
    ]],
    ["permissions.containers", [
        { containerIds: ["v"] }
    ]],
    ["permissions.organisations", [
        { organisationIds: [1] }
    ]],
    ["permissions.users", [
        { userIds: [1] }
    ]],
    ["permissions.roles", [{ roles: {} }]],
    ["permissions.tenants", [
        { tenantIds: [1] }
    ]],
    ["permissions.keys", [
        { keyIds: ["v"] }
    ]],
    ["permissions.edgeos", [
        { edgeosIds: ["v"] }
    ]],
    ["permissions.permissions", ["v"]],
    ["permissions.webhooks", [
        { webhookIds: ["v"] }
    ]],
    ["permissions.groups", [
        { groupIds: [1] }
    ]],

    ["edgeos.getAll", [1]],
    ["edgeos.getAll", [1, 1]],
    ["edgeos.getAll", [1, 1, "v"]],
    ["edgeos.getAll", [1, 1, "v", "v"]],
    ["edgeos.getAll", [1, 1, "v", "v", "v", 1]],
    ["edgeos.getAll", [1, 1, "v", "v", "v", 1, "v"]],
    ["edgeos.getAll", [1, 1, "v", "v", "v", 1, "v", "v"]],
    ["edgeos.getAll", [undefined]],
    ["edgeos.create", [{}]],
    ["edgeos.update", ["v", {}]],
    ["edgeos.get", ["valid"]],
    ["edgeos.delete", ["valid"]],

    ["tenants.create", [{}]],
    ["tenants.update", [1, {}]],
    ["tenants.get", [1]],
    ["tenants.getAll", [1]],
    ["tenants.getAll", [1, 1]],
    ["tenants.getAll", [1, 1, "v"]],
    ["tenants.getAll", [1, 1, "v", "v"]],
    ["tenants.delete", [1]],

    ["webhooks.create", [{}]],
    ["webhooks.test", [{}]],
    ["webhooks.delete", ["valid"]],
    ["webhooks.get", ["valid"]],
    ["webhooks.update", ["v", {}]],
    ["webhooks.update", ["v", {}]],
    ["webhooks.getAll", [1]],

    ["groups.get", [1, 1]],
    ["groups.get", [1]],
    ["groups.update", [1, {}]],
    ["groups.create", [1, {}]],
    ["groups.delete", [1]],
    ["groups.getGroupItems", [1],
        [1],
        [10],
        ["id"],
        ["asc"], {}
    ],
    ["groups.addDevice", [1, "v"]],
    ["groups.removeDevice", [1, "v"]],
    ["groups.addContainer", [1, "v"]],
    ["groups.removeContainer", [1, "v"]],
    ["groups.getAll", [1]],
    ["groups.getAll", [1, 1]],
    ["groups.getAll", [1, 1, 1]],
    ["groups.getAll", [1, 1, 1, "id"]],
    ["groups.getAll", [1, 1, 1, "id", "asc"]],
    ["groups.getAll", [1, 1, 1, "id", "asc", "devices"]],
    ["groups.getAll", [1, 1, 1, "id", "asc", "containers"]],

    ["deployments.filters.create", [{}]],
    ["deployments.filters.getAll", [1]],
    ["deployments.filters.getAll", [1, 1]],
    ["deployments.filters.getAll", [1, 1, 1]],
    ["deployments.filters.getAll", [1, 1, 1, "id"]],
    ["deployments.filters.getAll", [1, 1, 1, "id", "asc"]],
    ["deployments.filters.update", ["v", {}]],
    ["deployments.filters.delete", ["v"]],
    ["deployments.filters.get", ["v"]],
    ["deployments.filters.execute", [{}]],
    ["deployments.filters.execute", [{}, 1]],
    ["deployments.filters.execute", [{}, 1, 1]],
    ["deployments.filters.execute", [{}, 1, 1, "id"]],
    ["deployments.filters.execute", [{}, 1, 1, "id", "asc", "v"]],

    ["deployments.jobs.create", [{}]],
    ["deployments.jobs.update", ["v", {}]],
    ["deployments.jobs.delete", ["v"]],
    ["deployments.jobs.get", ["v"]],
    ["deployments.jobs.getAll", [1]],
    ["deployments.jobs.getAll", [1, 1]],
    ["deployments.jobs.getAll", [1, 1, 1]],
    ["deployments.jobs.getAll", [1, 1, 1, "id"]],
    ["deployments.jobs.getAll", [1, 1, 1, "id", "asc"]],
    ["deployments.jobs.execute", ['v', 'v']],
    ["deployments.jobs.execute", ['v', 'v', {}]],
    ["deployments.jobs.executeByGroup", ['v', 1]],
    ["deployments.jobs.executeByGroup", ['v', 1, {}]],
    ["deployments.jobs.executeCustomSelect", ['v', { "deviceIds": ["v"]}]],

    ["deployments.jobs.containers.add", ["v", "v", {}]],
    ["deployments.jobs.containers.update", ["v", "v", {}]],
    ["deployments.jobs.containers.delete", ["v", "v"]],
    ["deployments.jobs.containers.get", ["v", "v"]],
    ["deployments.jobs.containers.getAll", ["v"]],
    ["deployments.jobs.containers.getAll", ["v", 1]],
    ["deployments.jobs.containers.getAll", ["v", 1, 1]],
    ["deployments.jobs.containers.getAll", ["v", 1, 1, "id"]],
    ["deployments.jobs.containers.getAll", ["v", 1, 1, "id", "asc"]],

    ["deployments.jobs.containers.methods.add", ["v", "v", {}]],
    ["deployments.jobs.containers.methods.update", ["v", "v", "v", {}]],
    ["deployments.jobs.containers.methods.delete", ["v", "v", "v"]],
    ["deployments.jobs.containers.methods.get", ["v", "v", "v"]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v"]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v", 1]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v", 1, 1]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v", 1, 1, "id"]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v", 1, 1, "id", "asc"]],

    ["deployments.jobs.routes.add", ["v", {}]],
    ["deployments.jobs.routes.update", ["v", "v", {}]],
    ["deployments.jobs.routes.delete", ["v", "v"]],
    ["deployments.jobs.routes.get", ["v", "v"]],
    ["deployments.jobs.routes.getAll", ["v"]],
    ["deployments.jobs.routes.getAll", ["v", 1]],
    ["deployments.jobs.routes.getAll", ["v", 1, 1]],
    ["deployments.jobs.routes.getAll", ["v", 1, 1, "id"]],
    ["deployments.jobs.routes.getAll", ["v", 1, 1, "id", "asc"]],

    ["deployments.jobs.os.add", ["v", {}]],
    ["deployments.jobs.os.delete", ["v", "v"]],
    ["deployments.jobs.os.get", ["v", "v"]],
    ["deployments.jobs.os.getAll", ["v"]],
    ["deployments.jobs.os.getAll", ["v", 1]],
    ["deployments.jobs.os.getAll", ["v", 1, 1]],
    ["deployments.jobs.os.getAll", ["v", 1, 1, "id"]],
    ["deployments.jobs.os.getAll", ["v", 1, 1, "id", "asc"]],

    ["deployments.jobs.schedules.create", [{}]],
    ["deployments.jobs.schedules.update", ["v", {}]],
    ["deployments.jobs.schedules.delete", ["v"]],
    ["deployments.jobs.schedules.get", ["v"]],
    ["deployments.jobs.schedules.getAll", [1]],
    ["deployments.jobs.schedules.getAll", [1, 1]],
    ["deployments.jobs.schedules.getAll", [1, 1, 1]],
    ["deployments.jobs.schedules.getAll", [1, 1, 1, "id"]],
    ["deployments.jobs.schedules.getAll", [1, 1, 1, "id", "asc"]],

    ["deployments.rollouts.get", ["v"]],
    ["deployments.rollouts.getAll", [1]],
    ["deployments.rollouts.getAll", [1, 1]],
    ["deployments.rollouts.getAll", [1, 1, 1]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id"]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc"]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc", 'v']],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc", 'v', 'v']],
    ["deployments.rollouts.pause", ["v"]],
    ["deployments.rollouts.start", ["v"]],
    ["deployments.rollouts.rollback", ["v"]],
    ["deployments.rollouts.getRollbacks", ["v", "v"]],
    ["deployments.rollouts.delete", ["v"]],

    ["softwaremodules.modules.create", [
        [{}]
    ]],
    ["softwaremodules.modules.get", [1]],
    ["softwaremodules.modules.delete", [1]],
    ["softwaremodules.artifacts.create", [{}, 1]],
    ["softwaremodules.artifacts.get", [1, 1]],
    ["softwaremodules.orders.getAll", [1]],
    ["softwaremodules.orders.getAll", [1, 1]],
    ["softwaremodules.orders.getAll", [1, 1, 1]],
    ["softwaremodules.orders.getAll", [1, 1, 1, "name"]],
    ["softwaremodules.orders.getAll", [1, 1, 1, "name", "asc"]],
    ["softwaremodules.orders.get", [1]],

    ["metrics.query.create", [{}]],
    ["metrics.query.update", ["v", {}]],
    ["metrics.query.get", ["valid"]],
    ["metrics.query.getAll", [1]],
    ["metrics.query.getAll", [1, 1]],
    ["metrics.query.getAll", [1, 1, 1]],
    ["metrics.query.getAll", [1, 1, 1, "name"]],
    ["metrics.query.getAll", [1, 1, 1, "name", "asc"]],
    ["metrics.query.delete", ["valid"]],
    ["metrics.query.execute", ["2021", "2021", new FormData()]],
    ["metrics.query.executeSaved", [1, "v", "2021", "2021"]],
    ["metrics.query.executeSaved", [1, "v", "2021", "2021", "v"]],
    ["metrics.requestdata.get", ["valid"]],
    ["metrics.fields.get", []],

    ["bugreports.send", [{}]],

    ["announcements.getAll", []],
    ["announcements.getAll", ['v']],
    ["announcements.getAll", ['v', 'v']],
    ["announcements.getAll", ['v', 'v', 'v']],

    ["documentation.getAll", [1]],
    ["documentation.getAll", [1, 1]],
    ["documentation.getAll", [1, 1, "name"]],
    ["documentation.getAll", [1, 1, "name", "asc", 'v']],
    ["documentation.get", ['v', 'v']],
    ["documentation.versions.get", ['v', 'v', 'v']],

    ["resources.get", []],

    ["sessions.update", ['v']],
    ["sessions.get", ['v']],
    ["sessions.getAll", [1]],
    ["sessions.getAll", [1, 1]],
    ["sessions.getAll", [1, 1, "name"]],
    ["sessions.getAll", [1, 1, "name", "asc"]],

    ["sessions.getConnectionInfo", []],

    ["sessions.getConnectionDevices", [1]],
    ["sessions.getConnectionDevices", [1, 1]],
    ["sessions.getConnectionDevices", [1, 1, "name"]],
    ["sessions.getConnectionDevices", [1, 1, "name", "asc"]],
    ["sessions.getConnectionDevices", [1, 1, "name", "asc", []]],
    ["sessions.getConnectionDevices", [1, 1, "name", "asc", ["deviceid"]]],

    ["blocklists.create", [{}]],
    ["blocklists.delete", ['v']],
    ["blocklists.update", ['v', {}]],
    ["blocklists.get", ['v']],
    ["blocklists.getAll", [1]],
    ["blocklists.getAll", [1, 1]],
    ["blocklists.getAll", [1, 1, "name"]],
    ["blocklists.getAll", [1, 1, "name", "asc"]],

    ["pages.get", []],
    ["pages.get", ['v']],
    ["pages.templates.get", ['v']],
    ["pages.templates.get", ['v', 'v']],
];

describe("Correct Input Suite", function() {
    test.each(calls)(
        'sdk.%s with input %s works with promises',
        async(functionPath, validSignature) => {
            expect.assertions(1);
            const sdkFunction = _get(edgeSDK, functionPath);
            const result = await sdkFunction(...validSignature);
            expect(typeof result).toBe('object');
        },
    );

    test.each(calls)(
        'sdk.%s with input %s works with callbacks',
        async(functionPath, validSignature) => {
            const callback = jest.fn();
            const sdkFunction = _get(edgeSDK, functionPath);
            sdkFunction(...validSignature, callback);
            expect(callback).toBeCalled();
        },
    );
});
