/**********************************************************************
 * Copyright (c) 2021 Hilscher Gesellschaft fuer Systemautomation mbH
 * See LICENSE file
**********************************************************************/

const edgeSDK = require('../src/index');
const _get = require('lodash').get;
jest.mock('../src/client.js');

const suggestValid = {
    organisationId: 1,
    search: "valid",
};

const suggestValidTwo = {
    search: "valid",
};

const calls = [
    ["devices.customFields.delete", ["valid", "valid"]],
    ["devices.notifications.delete", ["valid", "valid"]],
    ["devices.customFields.get", ["valid", "valid"]],
    ["devices.create", [{}]],
    ["devices.onBoard", [{}]],
    ["devices.notifications.deleteAll", ["valid"]],
    ["devices.delete", ["valid"]],
    ["devices.get", ["valid"]],
    ["devices.offBoard", ["valid"]],
    ["devices.offBoardConfirm", [{}]],
    ["devices.create", [{}]],
    ["devices.getAll", [1]],
    ["devices.getAll", [1, 1]],
    ["devices.getAll", [1, 1, 1]],
    ["devices.getAll", [1, 1, 1, "name"]],
    ["devices.getAll", [1, 1, 1, "name", "asc"]],
    ["devices.getAll", [1, 1, 1, "name", "asc", "valid"]],
    ["devices.getStatusList", [["w", "w"]]],
    ["devices.methods", ["w", {}]],
    ["devices.update", ["w", {}]],
    ["devices.onBoard", [{}]],
    ["devices.onboardSesnorEdge", [{}]],
    ["devices.enableDisable", ["v", true, {}]],
    ["devices.enableDisable", ["v", false, {}]],
    ["devices.customFields.create", ["w", {}]],
    ["devices.customFields.update", ["v", "v", {}]],
    ["devices.notifications.create", ["v", {}]],
    ["devices.notifications.getAll", ["w"]],
    ["devices.notifications.getAll", ["w", 1,]],
    ["devices.notifications.getAll", ["w", 1, 1,]],
    ["devices.notifications.getAll", ["w", 1, 1, "w",]],
    ["devices.notifications.getAll", ["w", 1, 1, "w", "w"]],
    ["devices.customFields.getAll", ["w"]],
    ["devices.customFields.getAll", ["w", 1]],
    ["devices.customFields.getAll", ["w", 1, 1]],
    ["devices.customFields.getAll", ["w", 1, 1, "w"]],
    ["devices.customFields.getAll", ["w", 1, 1, "w", "w"]],
    ["devices.containers.routes.create", ["v", {}]],
    ["devices.containers.routes.update", ["v", "v", {}]],
    ["devices.containers.routes.getAll", ["valid"]],
    ["devices.containers.routes.get", ["valid", "valid"]],
    ["devices.containers.routes.delete", ["valid", "valid"]],
    ["devices.containers.get", ["valid", "valid"]],
    ["devices.containers.getInstalled", ["valid"]],
    ["devices.containers.getInstalled", ["w", 1]],
    ["devices.containers.getInstalled", ["w", 1, 1]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w"]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w", "w"]],
    ["devices.containers.getInstalled", ["w", 1, 1, "w", "w", "all"]],
    ["devices.containers.getDeployable", ["valid"]],
    ["devices.containers.getDeployable", ["w", 1]],
    ["devices.containers.getDeployable", ["w", 1, 1]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w"]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w"]],
    ["devices.containers.getDeployable", ["w", 1, 1, "w", "w", false]],
    ["devices.containers.delete", ["valid", "valid"]],
    ["devices.containers.create", ["valid", "valid", {}]],
    ["devices.containers.update", ["valid", "valid", {}]],
    ["devices.containers.properties", ["valid", "valid"]],
    ["devices.containers.deleteAll", ["v"]],
    ["devices.remote.create", ["valid", {}]],
    ["devices.remote.status", ["valid"]],
    ["devices.remote.credentials", ["valid"]],
    ["devices.deploymentManifests.check", ["valid"]],
    ["devices.deploymentManifests.deploy", ["valid"]],

    ["dashboards.create", [{}]],
    ["dashboards.update", ["v", {}]],
    ["dashboards.get", ["v"]],
    ["dashboards.getAll", [1]],
    ["dashboards.getAll", [1, 1]],
    ["dashboards.getAll", [1, 1, 1]],
    ["dashboards.getAll", [1, 1, 1, "name"]],
    ["dashboards.getAll", [1, 1, 1, "name", "asc"]],
    ["dashboards.delete", ["v"]],
    ["dashboards.panels.create", ["v", {}]],
    ["dashboards.panels.update", ["v", "v", {}]],
    ["dashboards.panels.get", ["v", "v"]],
    ["dashboards.panels.getAll", ["v"]],
    ["dashboards.panels.delete", ["v", "v"]],
    ["dashboards.series.create", ["v", "v", {}]],
    ["dashboards.series.update", ["v", "v", "v", {}]],
    ["dashboards.series.get", ["v", "v", "v"]],
    ["dashboards.series.getAll", ["v", "v"]],
    ["dashboards.series.delete", ["v", "v", "v"]],

    ["containers.create", [{}]],
    ["containers.delete", ["valid"]],
    ["containers.delete", ["valid", true]],
    ["containers.delete", ["valid", false]],
    ["containers.get", ["valid"]],
    ["containers.update", ["v", {}]],
    ["containers.update", ["v", {}]],
    ["containers.getAll", []],
    ["containers.getAll", [1, 1, "name", "asc", true]],
    ["containers.getAll", [1, 1, "name", "asc", false]],
    ["containers.share", ["v", [1]]],
    ["containers.unshare", ["v", 1]],
    ["containers.versions.createversion", [{}, "v"]],
    ["containers.versions.deleteversion", ["v", "v"]],
    ["containers.versions.getversion", ["v", "v"]],
    ["containers.versions.getallversions", ["v"]],
    ["containers.versions.getallversions", ["v", 1]],
    ["containers.versions.getallversions", ["v", 1, 1]],
    ["containers.versions.getallversions", ["v", 1, 1, "name"]],
    ["containers.versions.updateversion", [{}, "v", "v"]],
    ["containers.disable", ["v", {}]],

    ["sensoredgemanifest.create", [{}]],
    ["sensoredgemanifest.delete", ["valid"]],
    ["sensoredgemanifest.get", ["valid"]],
    ["sensoredgemanifest.update", ["v", {}]],
    ["sensoredgemanifest.update", ["v", {}]],
    ["sensoredgemanifest.getAll", []],
    ["sensoredgemanifest.uploadOs", [{}]],

    ["users.createself", [{}]],
    ["users.create", [{}]],
    ["users.sensoredge.create", [{}]],
    ["users.profile.update", [{}]],
    ["users.profile.notificationEmails.add", [{}]],
    ["users.profile.notificationEmails.getAll", []],
    ["users.profile.notificationEmails.getAll", [1]],
    ["users.profile.notificationEmails.getAll", [1, 1]],
    ["users.profile.notificationEmails.getAll", [1, 1, 'v']],
    ["users.profile.notificationEmails.getAll", [1, 1, 'v', 'asc']],
    ["users.profile.notificationEmails.delete", [1]],
    ["users.verifyusers", [{}]],
    ["users.sensoredge.verify", [{}]],
    ["users.sensoredge.getverify", ["v"]],
    ["users.getAll", [1]],
    ["users.getAll", [1, 1]],
    ["users.getAll", [1, 1, 1]],
    ["users.getAll", [1, 1, 1, "name"]],
    ["users.getAll", [1, 1, 1, "name", "asc"]],
    ["users.get", [1]],
    ["users.getverify", ["valid"]],
    ["users.update", [1, {}]],
    ["users.sensoredge.completeRegistration", [{}]],
    ["users.delete", [1]],
    ["users.roles.add", [1, "valid"]],
    ["users.roles.delete", [1, "valid"]],
    ["users.roles.getAll", [1]],
    ["users.roles.getAll", [1, 1]],
    ["users.roles.getAll", [1, 1, 1]],
    ["users.roles.getAll", [1, 1, 1, "name"]],
    ["users.roles.getAll", [1, 1, 1, "name", "asc"]],
    ["users.suggest", [suggestValid]],
    ["users.suggest", [suggestValidTwo]],

    ["keys.create", [{}]],
    ["keys.delete", ["valid"]],
    ["keys.get", ["valid"]],
    ["keys.update", ["v", {}]],
    ["keys.getAll", [1]],
    ["keys.getAll", [1, 1]],
    ["keys.getAll", [1, 1, 1]],
    ["keys.getAll", [1, 1, 1, "v",]],
    ["keys.getAll", [1, 1, 1, "v", "v"]],
    ["keys.createSensorEdgeKey", [{}]],

    ["auth.resetPassword", ["valid"]],
    ["auth.setPassword", [{}]],

    ["organisation.get", [1, 1]],
    ["organisation.get", [1]],
    ["organisation.getAll", []],
    ["organisation.getAll", [1]],
    ["organisation.getAll", [1, 1, 'v']],
    ["organisation.getAll", [1, 1, 'v', 'v']],
    ["organisation.getAll", [1, 1, 'v', 'v', 'v']],
    ["organisation.update", [1, {}]],
    ["organisation.create", [1, {}]],
    ["organisation.delete", [1]],

    ["organisation.manifest.createContainer", [1, "v", {}]],
    ["organisation.manifest.createRoute", [1, {}]],
    ["organisation.manifest.getContainers", [1]],
    ["organisation.manifest.getRoutes", [1]],
    ["organisation.manifest.deleteContainer", [1, "name"]],
    ["organisation.manifest.deleteRoute", [1, "name"]],
    ["organisation.manifest.updateContainer", [1, "w", {}]],
    ["organisation.manifest.updateRoute", [1, "w", {}]],
    ["organisation.manifest.getContainer", [1, "w"]],
    ["organisation.manifest.getRoute", [1, "name"]],
    ["organisation.manifest.copyManifest", [1]],
    ["organisation.manifest.applyManifest", [1, 'valid']],

    ["roles.create", [1, {}]],
    ["roles.get", [1, "v"]],
    ["roles.update", [1, "v", {}]],
    ["roles.getAll", [1]],
    ["roles.getAll", [1, 1]],
    ["roles.getAll", [1, 1, 1]],
    ["roles.getAll", [1, 1, 1, "name"]],
    ["roles.getAll", [1, 1, 1, "name", "asc"]],
    ["roles.delete", [1, "v"]],

    ["search.devices", ["v"]],
    ["search.devices", ["v", "v"]],
    ["search.devices", ["v", ["v"]]],
    ["search.devices", ["v", "v", "fuzzy"]],
    ["search.devices", ["v", "v", "fuzzy", 1]],
    ["search.devices", ["v", "v", "fuzzy", 1, 1]],
    ["search.devices", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.devices", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.containers", ["v"]],
    ["search.containers", ["v", "v"]],
    ["search.containers", ["v", ["v"]]],
    ["search.containers", ["v", "v", "fuzzy"]],
    ["search.containers", ["v", "v", "fuzzy", 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 'asc', true]],
    ["search.containers", ["v", "v", "fuzzy", 1, 1, 'name', 'asc', false]],
    ["search.users", ["v"]],
    ["search.users", ["v", "v"]],
    ["search.users", ["v", ["v"]]],
    ["search.users", ["v", "v", "fuzzy"]],
    ["search.users", ["v", "v", "fuzzy", 1]],
    ["search.users", ["v", "v", "fuzzy", 1, 1]],
    ["search.users", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.users", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.organisations", ["v"]],
    ["search.organisations", ["v", "v"]],
    ["search.organisations", ["v", ["v"]]],
    ["search.organisations", ["v", "v", "fuzzy"]],
    ["search.organisations", ["v", "v", "fuzzy", 1]],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1]],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.organisations", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.deploymentFilters", ["v"]],
    ["search.deploymentFilters", ["v", "v"]],
    ["search.deploymentFilters", ["v", ["v"]]],
    ["search.deploymentFilters", ["v", "v", "fuzzy"]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1]],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.deploymentFilters", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.deploymentJobs", ["v"]],
    ["search.deploymentJobs", ["v", "v"]],
    ["search.deploymentJobs", ["v", ["v"]]],
    ["search.deploymentJobs", ["v", "v", "fuzzy"]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1]],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1, 'name']],
    ["search.deploymentJobs", ["v", "v", "fuzzy", 1, 1, 'name', 'asc']],
    ["search.deploymentRollouts", ["v"]],
    ["search.deploymentRollouts", ["v", "v"]],
    ["search.deploymentRollouts", ["v", ["v"]]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy"]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1]],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1, 'jobName']],
    ["search.deploymentRollouts", ["v", "v", "fuzzy", 1, 1, 'jobName', 'asc']],


    ["permissions.devices", [["v", "v"]]],
    ["permissions.containers", [["v", "v"]]],
    ["permissions.organisations", [[1, 1, 1]]],
    ["permissions.users", [[1, 1, 1]]],
    ["permissions.roles", [{}]],
    ["permissions.tenants", [[1, 1, 1]]],
    ["permissions.keys", [["v", "v"]]],
    ["permissions.edgeos", [["v", "v"]]],
    ["permissions.permissions", ["v"]],
    ["permissions.webhooks", [["v", "v"]]],
    ["permissions.groups", [[1, 1, 1]]],

    ["edgeos.getAll", [1]],
    ["edgeos.getAll", [1, 1]],
    ["edgeos.getAll", [1, 1, "v"]],
    ["edgeos.getAll", [1, 1, "v", "v"]],
    ["edgeos.getAll", [1, 1, "v", "v", "v"]],
    ["edgeos.getAll", [1, 1, "v", "v", "v", 1]],
    ["edgeos.getAll", [undefined]],
    ["edgeos.create", [{}]],
    ["edgeos.update", ["v", {}]],
    ["edgeos.get", ["valid"]],
    ["edgeos.delete", ["valid"]],

    ["tenants.create", [{}]],
    ["tenants.update", [1, {}]],
    ["tenants.get", [1]],
    ["tenants.getAll", [1]],
    ["tenants.getAll", [1, 1]],
    ["tenants.getAll", [1, 1, "v"]],
    ["tenants.getAll", [1, 1, "v", "v"]],
    ["tenants.delete", [1]],

    ["webhooks.create", [{}]],
    ["webhooks.test", [{}]],
    ["webhooks.delete", ["valid"]],
    ["webhooks.get", ["valid"]],
    ["webhooks.update", ["v", {}]],
    ["webhooks.update", ["v", {}]],
    ["webhooks.getAll", [1]],

    ["groups.get", [1, 1]],
    ["groups.get", [1]],
    ["groups.update", [1, {}]],
    ["groups.create", [1, {}]],
    ["groups.delete", [1]],
    ["groups.getGroupItems", [1], [1], [10], ["id"], ["asc"], {}],
    ["groups.addDevice", [1, "v"]],
    ["groups.removeDevice", [1, "v"]],
    ["groups.addContainer", [1, "v"]],
    ["groups.removeContainer", [1, "v"]],

    ["deployments.filters.create", [{}]],
    ["deployments.filters.getAll", [1]],
    ["deployments.filters.getAll", [1, 1]],
    ["deployments.filters.getAll", [1, 1, 1]],
    ["deployments.filters.getAll", [1, 1, 1, "id"]],
    ["deployments.filters.getAll", [1, 1, 1, "id", "asc"]],
    ["deployments.filters.update", ["v", {}]],
    ["deployments.filters.delete", ["v"]],
    ["deployments.filters.get", ["v"]],
    ["deployments.filters.execute", [{}]],
    ["deployments.filters.execute", [{}, 1]],
    ["deployments.filters.execute", [{}, 1, 1]],
    ["deployments.filters.execute", [{}, 1, 1, "id"]],
    ["deployments.filters.execute", [{}, 1, 1, "id", "asc"]],

    ["deployments.jobs.create", [{}]],
    ["deployments.jobs.update", ["v", {}]],
    ["deployments.jobs.delete", ["v"]],
    ["deployments.jobs.get", ["v"]],
    ["deployments.jobs.getAll", [1]],
    ["deployments.jobs.getAll", [1, 1]],
    ["deployments.jobs.getAll", [1, 1, 1]],
    ["deployments.jobs.getAll", [1, 1, 1, "id"]],
    ["deployments.jobs.getAll", [1, 1, 1, "id", "asc"]],
    ["deployments.jobs.execute", ['v', 'v']],
    ["deployments.jobs.execute", ['v', 'v', {}]],

    ["deployments.jobs.containers.add", ["v", "v", {}]],
    ["deployments.jobs.containers.update", ["v", "v", {}]],
    ["deployments.jobs.containers.delete", ["v", "v"]],
    ["deployments.jobs.containers.get", ["v", "v"]],
    ["deployments.jobs.containers.getAll", ["v"]],
    ["deployments.jobs.containers.getAll", ["v", 1]],
    ["deployments.jobs.containers.getAll", ["v", 1, 1]],
    ["deployments.jobs.containers.getAll", ["v", 1, 1, "id"]],
    ["deployments.jobs.containers.getAll", ["v", 1, 1, "id", "asc"]],

    ["deployments.jobs.containers.methods.add", ["v", "v", {}]],
    ["deployments.jobs.containers.methods.update", ["v", "v", "v", {}]],
    ["deployments.jobs.containers.methods.delete", ["v", "v", "v"]],
    ["deployments.jobs.containers.methods.get", ["v", "v", "v"]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v"]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v", 1]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v", 1, 1]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v", 1, 1, "id"]],
    ["deployments.jobs.containers.methods.getAll", ["v", "v", 1, 1, "id", "asc"]],

    ["deployments.jobs.routes.add", ["v", {}]],
    ["deployments.jobs.routes.update", ["v", "v", {}]],
    ["deployments.jobs.routes.delete", ["v", "v"]],
    ["deployments.jobs.routes.get", ["v", "v"]],
    ["deployments.jobs.routes.getAll", ["v"]],
    ["deployments.jobs.routes.getAll", ["v", 1]],
    ["deployments.jobs.routes.getAll", ["v", 1, 1]],
    ["deployments.jobs.routes.getAll", ["v", 1, 1, "id"]],
    ["deployments.jobs.routes.getAll", ["v", 1, 1, "id", "asc"]],

    ["deployments.rollouts.get", ["v"]],
    ["deployments.rollouts.getAll", [1]],
    ["deployments.rollouts.getAll", [1, 1]],
    ["deployments.rollouts.getAll", [1, 1, 1]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id"]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc"]],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc", 'v']],
    ["deployments.rollouts.getAll", [1, 1, 1, "id", "asc", 'v', 'v']],
    ["deployments.rollouts.pause", ["v"]],
    ["deployments.rollouts.start", ["v"]],
    ["deployments.rollouts.rollback", ["v"]],
    ["deployments.rollouts.getRollbacks", ["v", "v"]],

    ["softwaremodules.modules.create", [[{}]]],
    ["softwaremodules.modules.get", [1]],
    ["softwaremodules.artifacts.create", [{}, 1]],
    ["softwaremodules.artifacts.get", [1, 1]],
    ["softwaremodules.orders.getAll", [1]],
    ["softwaremodules.orders.getAll", [1, 1]],
    ["softwaremodules.orders.getAll", [1, 1, 1]],
    ["softwaremodules.orders.getAll", [1, 1, 1, "name"]],
    ["softwaremodules.orders.getAll", [1, 1, 1, "name", "asc"]],
    ["softwaremodules.orders.get", [1]],
];

describe("Correct Input Suite", function () {
    test.each(calls)(
        'sdk.%s with input %s works with promises',
        async (functionPath, validSignature) => {
            expect.assertions(1);
            const sdkFunction = _get(edgeSDK, functionPath);
            const result = await sdkFunction(...validSignature);
            expect(typeof result).toBe('object');
        },
    );

    test.each(calls)(
        'sdk.%s with input %s works with callbacks',
        async (functionPath, validSignature) => {
            const callback = jest.fn();
            const sdkFunction = _get(edgeSDK, functionPath);
            sdkFunction(...validSignature, callback);
            expect(callback).toBeCalled();
        },
    );
});
